export const CITIES = [
  // --- ANDAMAN AND NICOBAR ISLANDS ---
  { id: 'port-blair', name: 'Port Blair', state: 'Andaman and Nicobar Islands', country: 'India', lat: 11.6234, lng: 92.7265, tz: 5.5, nameHi: 'पोर्ट ब्लेयर' },

  // --- ANDHRA PRADESH ---
  { id: 'adoni', name: 'Adoni', state: 'Andhra Pradesh', country: 'India', lat: 15.6322, lng: 77.2728, tz: 5.5, nameHi: 'आदोनी' },
  { id: 'amaravati', name: 'Amaravati', state: 'Andhra Pradesh', country: 'India', lat: 16.5735, lng: 80.3575, tz: 5.5, nameHi: 'अमरावती' },
  { id: 'anantapur', name: 'Anantapur', state: 'Andhra Pradesh', country: 'India', lat: 14.6819, lng: 77.6006, tz: 5.5, nameHi: 'अनंतपुर' },
  { id: 'chandragiri', name: 'Chandragiri', state: 'Andhra Pradesh', country: 'India', lat: 13.5855, lng: 79.3175, tz: 5.5, nameHi: 'चन्द्रगिरि' },
  { id: 'chittoor', name: 'Chittoor', state: 'Andhra Pradesh', country: 'India', lat: 13.2172, lng: 79.1003, tz: 5.5, nameHi: 'चित्तूर' },
  { id: 'dowlaiswaram', name: 'Dowlaiswaram', state: 'Andhra Pradesh', country: 'India', lat: 16.9405, lng: 81.7766, tz: 5.5, nameHi: 'धवलेश्वरम' },
  { id: 'eluru', name: 'Eluru', state: 'Andhra Pradesh', country: 'India', lat: 16.7107, lng: 81.0952, tz: 5.5, nameHi: 'एलुरु' },
  { id: 'guntur', name: 'Guntur', state: 'Andhra Pradesh', country: 'India', lat: 16.3067, lng: 80.4365, tz: 5.5, nameHi: 'गुंटूर' },
  { id: 'kadapa', name: 'Kadapa', state: 'Andhra Pradesh', country: 'India', lat: 14.4673, lng: 78.8242, tz: 5.5, nameHi: 'कडपा' },
  { id: 'kakinada', name: 'Kakinada', state: 'Andhra Pradesh', country: 'India', lat: 16.9891, lng: 82.2475, tz: 5.5, nameHi: 'काकीनाडा' },
  { id: 'kurnool', name: 'Kurnool', state: 'Andhra Pradesh', country: 'India', lat: 15.8281, lng: 78.0373, tz: 5.5, nameHi: 'कर्नूल' },
  { id: 'machilipatnam', name: 'Machilipatnam', state: 'Andhra Pradesh', country: 'India', lat: 16.1875, lng: 81.1389, tz: 5.5, nameHi: 'मछलीपट्टनम' },
  { id: 'nagarjunakonda', name: 'Nagarjunakonda', state: 'Andhra Pradesh', country: 'India', lat: 16.5250, lng: 79.3178, tz: 5.5, nameHi: 'नागार्जुनकोण्ड' },
  { id: 'rajahmundry', name: 'Rajahmundry', state: 'Andhra Pradesh', country: 'India', lat: 17.0005, lng: 81.8040, tz: 5.5, nameHi: 'राजमंड्री' },
  { id: 'srikakulam', name: 'Srikakulam', state: 'Andhra Pradesh', country: 'India', lat: 18.2949, lng: 83.8938, tz: 5.5, nameHi: 'श्रीकाकुलम' },
  { id: 'tirupati', name: 'Tirupati', state: 'Andhra Pradesh', country: 'India', lat: 13.6288, lng: 79.4192, tz: 5.5, nameHi: 'तिरुपति', isPopular: true },
  { id: 'vijayawada', name: 'Vijayawada', state: 'Andhra Pradesh', country: 'India', lat: 16.5062, lng: 80.6480, tz: 5.5, nameHi: 'विजयवाड़ा', isPopular: true },
  { id: 'visakhapatnam', name: 'Visakhapatnam', state: 'Andhra Pradesh', country: 'India', lat: 17.6868, lng: 83.2185, tz: 5.5, nameHi: 'विशाखापट्टनम', isPopular: true },
  { id: 'vizianagaram', name: 'Vizianagaram', state: 'Andhra Pradesh', country: 'India', lat: 18.1067, lng: 83.3956, tz: 5.5, nameHi: 'विजयनगरम' },
  { id: 'yemmiganur', name: 'Yemmiganur', state: 'Andhra Pradesh', country: 'India', lat: 15.7338, lng: 77.4789, tz: 5.5, nameHi: 'एम्मिगनूर' },

  // --- ARUNACHAL PRADESH ---
  { id: 'itanagar', name: 'Itanagar', state: 'Arunachal Pradesh', country: 'India', lat: 27.0844, lng: 93.6053, tz: 5.5, nameHi: 'ईटानगर' },

  // --- ASSAM ---
  { id: 'dhuburi', name: 'Dhuburi', state: 'Assam', country: 'India', lat: 26.0199, lng: 89.9749, tz: 5.5, nameHi: 'धुबरी' },
  { id: 'dibrugarh', name: 'Dibrugarh', state: 'Assam', country: 'India', lat: 27.4728, lng: 94.9120, tz: 5.5, nameHi: 'डिब्रूगढ़' },
  { id: 'dispur', name: 'Dispur', state: 'Assam', country: 'India', lat: 26.1433, lng: 91.7898, tz: 5.5, nameHi: 'दिसपुर' },
  { id: 'guwahati', name: 'Guwahati', state: 'Assam', country: 'India', lat: 26.1445, lng: 91.7362, tz: 5.5, nameHi: 'गुवाहाटी', isPopular: true },
  { id: 'jorhat', name: 'Jorhat', state: 'Assam', country: 'India', lat: 26.7509, lng: 94.2037, tz: 5.5, nameHi: 'जोरहाट' },
  { id: 'nagaon', name: 'Nagaon', state: 'Assam', country: 'India', lat: 26.3468, lng: 92.6840, tz: 5.5, nameHi: 'नगांव' },
  { id: 'sivasagar', name: 'Sivasagar', state: 'Assam', country: 'India', lat: 26.9826, lng: 94.6425, tz: 5.5, nameHi: 'शिवसागर' },
  { id: 'silchar', name: 'Silchar', state: 'Assam', country: 'India', lat: 24.8333, lng: 92.7789, tz: 5.5, nameHi: 'सिलचर' },
  { id: 'tezpur', name: 'Tezpur', state: 'Assam', country: 'India', lat: 26.6528, lng: 92.7926, tz: 5.5, nameHi: 'तेजपुर' },
  { id: 'tinsukia', name: 'Tinsukia', state: 'Assam', country: 'India', lat: 27.4922, lng: 95.3468, tz: 5.5, nameHi: 'तिनसुकिया' },

  // --- BIHAR ---
  { id: 'ara', name: 'Ara', state: 'Bihar', country: 'India', lat: 25.5541, lng: 84.6644, tz: 5.5, nameHi: 'आरा' },
  { id: 'barauni', name: 'Barauni', state: 'Bihar', country: 'India', lat: 25.4746, lng: 85.9723, tz: 5.5, nameHi: 'बरौनी' },
  { id: 'begusarai', name: 'Begusarai', state: 'Bihar', country: 'India', lat: 25.4182, lng: 86.1272, tz: 5.5, nameHi: 'बेगूसराय' },
  { id: 'bettiah', name: 'Bettiah', state: 'Bihar', country: 'India', lat: 26.8025, lng: 84.5029, tz: 5.5, nameHi: 'बेतिया' },
  { id: 'bhagalpur', name: 'Bhagalpur', state: 'Bihar', country: 'India', lat: 25.2425, lng: 86.9842, tz: 5.5, nameHi: 'भागलपुर' },
  { id: 'bihar-sharif', name: 'Bihar Sharif', state: 'Bihar', country: 'India', lat: 25.1982, lng: 85.5186, tz: 5.5, nameHi: 'बिहार शरीफ' },
  { id: 'bodh-gaya', name: 'Bodh Gaya', state: 'Bihar', country: 'India', lat: 24.6961, lng: 84.9869, tz: 5.5, nameHi: 'बोधगया', isPopular: true },
  { id: 'buxar', name: 'Buxar', state: 'Bihar', country: 'India', lat: 25.5647, lng: 83.9777, tz: 5.5, nameHi: 'बक्सर' },
  { id: 'chapra', name: 'Chapra', state: 'Bihar', country: 'India', lat: 25.7796, lng: 84.7499, tz: 5.5, nameHi: 'छपरा' },
  { id: 'darbhanga', name: 'Darbhanga', state: 'Bihar', country: 'India', lat: 26.1542, lng: 85.8918, tz: 5.5, nameHi: 'दरभंगा' },
  { id: 'dehri', name: 'Dehri', state: 'Bihar', country: 'India', lat: 24.9080, lng: 84.1852, tz: 5.5, nameHi: 'डेहरी' },
  { id: 'dinapur-nizamat', name: 'Dinapur Nizamat', state: 'Bihar', country: 'India', lat: 25.6323, lng: 85.0440, tz: 5.5, nameHi: 'दानापुर' },
  { id: 'gaya', name: 'Gaya', state: 'Bihar', country: 'India', lat: 24.7914, lng: 85.0002, tz: 5.5, nameHi: 'गया जी', isPopular: true },
  { id: 'hajipur', name: 'Hajipur', state: 'Bihar', country: 'India', lat: 25.6858, lng: 85.2146, tz: 5.5, nameHi: 'हाजीपुर' },
  { id: 'jamalpur', name: 'Jamalpur', state: 'Bihar', country: 'India', lat: 25.3129, lng: 86.4950, tz: 5.5, nameHi: 'जमालपुर' },
  { id: 'katihar', name: 'Katihar', state: 'Bihar', country: 'India', lat: 25.5541, lng: 87.5716, tz: 5.5, nameHi: 'कटिहार' },
  { id: 'madhubani', name: 'Madhubani', state: 'Bihar', country: 'India', lat: 26.3546, lng: 86.0718, tz: 5.5, nameHi: 'मधुबनी' },
  { id: 'motihari', name: 'Motihari', state: 'Bihar', country: 'India', lat: 26.6469, lng: 84.9089, tz: 5.5, nameHi: 'मोतिहारी' },
  { id: 'munger', name: 'Munger', state: 'Bihar', country: 'India', lat: 25.3757, lng: 86.4744, tz: 5.5, nameHi: 'मुंगेर' },
  { id: 'muzaffarpur', name: 'Muzaffarpur', state: 'Bihar', country: 'India', lat: 26.1209, lng: 85.3647, tz: 5.5, nameHi: 'मुजफ्फरपुर' },
  { id: 'patna', name: 'Patna', state: 'Bihar', country: 'India', lat: 25.5941, lng: 85.1376, tz: 5.5, nameHi: 'पटना', isPopular: true },
  { id: 'purnia', name: 'Purnia', state: 'Bihar', country: 'India', lat: 25.7771, lng: 87.4753, tz: 5.5, nameHi: 'पूर्णिया' },
  { id: 'pusa', name: 'Pusa', state: 'Bihar', country: 'India', lat: 25.9833, lng: 85.6667, tz: 5.5, nameHi: 'पूसा' },
  { id: 'saharsa', name: 'Saharsa', state: 'Bihar', country: 'India', lat: 25.8835, lng: 86.6006, tz: 5.5, nameHi: 'सहरसा' },
  { id: 'samastipur', name: 'Samastipur', state: 'Bihar', country: 'India', lat: 25.8629, lng: 85.7811, tz: 5.5, nameHi: 'समस्तीपुर' },
  { id: 'sasaram', name: 'Sasaram', state: 'Bihar', country: 'India', lat: 24.9515, lng: 84.0297, tz: 5.5, nameHi: 'सासाराम' },
  { id: 'sitamarhi', name: 'Sitamarhi', state: 'Bihar', country: 'India', lat: 26.5936, lng: 85.4893, tz: 5.5, nameHi: 'सीतामढ़ी' },
  { id: 'siwan', name: 'Siwan', state: 'Bihar', country: 'India', lat: 26.2196, lng: 84.3567, tz: 5.5, nameHi: 'सीवान' },

  // --- CHANDIGARH ---
  { id: 'chandigarh', name: 'Chandigarh', state: 'Chandigarh', country: 'India', lat: 30.7333, lng: 76.7794, tz: 5.5, nameHi: 'चण्डीगढ़', isPopular: true },

  // --- CHHATTISGARH ---
  { id: 'ambikapur', name: 'Ambikapur', state: 'Chhattisgarh', country: 'India', lat: 23.1187, lng: 83.1979, tz: 5.5, nameHi: 'अम्बिकापुर' },
  { id: 'bhilai', name: 'Bhilai', state: 'Chhattisgarh', country: 'India', lat: 21.1938, lng: 81.3509, tz: 5.5, nameHi: 'भिलाई' },
  { id: 'bilaspur-cg', name: 'Bilaspur', state: 'Chhattisgarh', country: 'India', lat: 22.0797, lng: 82.1409, tz: 5.5, nameHi: 'बिलासपुर' },
  { id: 'dhamtari', name: 'Dhamtari', state: 'Chhattisgarh', country: 'India', lat: 20.7071, lng: 81.5497, tz: 5.5, nameHi: 'धमतरी' },
  { id: 'durg', name: 'Durg', state: 'Chhattisgarh', country: 'India', lat: 21.1904, lng: 81.2849, tz: 5.5, nameHi: 'दुर्ग' },
  { id: 'jagdalpur', name: 'Jagdalpur', state: 'Chhattisgarh', country: 'India', lat: 19.0732, lng: 82.0223, tz: 5.5, nameHi: 'जगदलपुर' },
  { id: 'raipur', name: 'Raipur', state: 'Chhattisgarh', country: 'India', lat: 21.2514, lng: 81.6296, tz: 5.5, nameHi: 'रायपुर', isPopular: true },
  { id: 'rajnandgaon', name: 'Rajnandgaon', state: 'Chhattisgarh', country: 'India', lat: 21.0974, lng: 81.0388, tz: 5.5, nameHi: 'राजनंदगांव' },

  // --- DADRA AND NAGAR HAVELI AND DAMAN AND DIU ---
  { id: 'daman', name: 'Daman', state: 'Dadra and Nagar Haveli and Daman and Diu', country: 'India', lat: 20.3974, lng: 72.8328, tz: 5.5, nameHi: 'दमन' },
  { id: 'diu', name: 'Diu', state: 'Dadra and Nagar Haveli and Daman and Diu', country: 'India', lat: 20.7144, lng: 70.9874, tz: 5.5, nameHi: 'दीव' },
  { id: 'silvassa', name: 'Silvassa', state: 'Dadra and Nagar Haveli and Daman and Diu', country: 'India', lat: 20.2763, lng: 73.0083, tz: 5.5, nameHi: 'सिलवासा' },

  // --- DELHI ---
  { id: 'delhi', name: 'Delhi', state: 'Delhi', country: 'India', lat: 28.7041, lng: 77.1025, tz: 5.5, nameHi: 'दिल्ली', isPopular: true },
  { id: 'new-delhi', name: 'New Delhi', state: 'Delhi', country: 'India', lat: 28.6139, lng: 77.2090, tz: 5.5, nameHi: 'नई दिल्ली', isPopular: true },

  // --- GOA ---
  { id: 'madgaon', name: 'Madgaon', state: 'Goa', country: 'India', lat: 15.2832, lng: 73.9862, tz: 5.5, nameHi: 'मडगांव (मार्गौ)' },
  { id: 'panaji', name: 'Panaji', state: 'Goa', country: 'India', lat: 15.4909, lng: 73.8278, tz: 5.5, nameHi: 'पणजी', isPopular: true },

  // --- GUJARAT ---
  { id: 'ahmedabad', name: 'Ahmadabad', state: 'Gujarat', country: 'India', lat: 23.0225, lng: 72.5714, tz: 5.5, nameHi: 'अहमदाबाद', isPopular: true },
  { id: 'amreli', name: 'Amreli', state: 'Gujarat', country: 'India', lat: 21.6032, lng: 71.2221, tz: 5.5, nameHi: 'अमरेली' },
  { id: 'bharuch', name: 'Bharuch', state: 'Gujarat', country: 'India', lat: 21.7051, lng: 72.9959, tz: 5.5, nameHi: 'भरूच' },
  { id: 'bhavnagar', name: 'Bhavnagar', state: 'Gujarat', country: 'India', lat: 21.7645, lng: 72.1519, tz: 5.5, nameHi: 'भावनगर' },
  { id: 'bhuj', name: 'Bhuj', state: 'Gujarat', country: 'India', lat: 23.2420, lng: 69.6669, tz: 5.5, nameHi: 'भुज' },
  { id: 'dwarka', name: 'Dwarka', state: 'Gujarat', country: 'India', lat: 22.2442, lng: 68.9685, tz: 5.5, nameHi: 'द्वारका धाम', isPopular: true },
  { id: 'gandhinagar', name: 'Gandhinagar', state: 'Gujarat', country: 'India', lat: 23.2156, lng: 72.6369, tz: 5.5, nameHi: 'गांधीनगर' },
  { id: 'godhra', name: 'Godhra', state: 'Gujarat', country: 'India', lat: 22.7758, lng: 73.6149, tz: 5.5, nameHi: 'गोधरा' },
  { id: 'jamnagar', name: 'Jamnagar', state: 'Gujarat', country: 'India', lat: 22.4707, lng: 70.0577, tz: 5.5, nameHi: 'जामनगर' },
  { id: 'junagadh', name: 'Junagadh', state: 'Gujarat', country: 'India', lat: 21.5222, lng: 70.4579, tz: 5.5, nameHi: 'जूनागढ़' },
  { id: 'kandla', name: 'Kandla', state: 'Gujarat', country: 'India', lat: 23.0113, lng: 70.2185, tz: 5.5, nameHi: 'कांडला' },
  { id: 'khambhat', name: 'Khambhat', state: 'Gujarat', country: 'India', lat: 22.3131, lng: 72.6193, tz: 5.5, nameHi: 'खंभात' },
  { id: 'kheda', name: 'Kheda', state: 'Gujarat', country: 'India', lat: 22.7533, lng: 72.6841, tz: 5.5, nameHi: 'खेड़ा' },
  { id: 'mahesana', name: 'Mahesana', state: 'Gujarat', country: 'India', lat: 23.5880, lng: 72.3693, tz: 5.5, nameHi: 'महेसाणा' },
  { id: 'morbi', name: 'Morbi', state: 'Gujarat', country: 'India', lat: 22.8120, lng: 70.8384, tz: 5.5, nameHi: 'मोरबी' },
  { id: 'nadiad', name: 'Nadiad', state: 'Gujarat', country: 'India', lat: 22.6916, lng: 72.8634, tz: 5.5, nameHi: 'नडियाद' },
  { id: 'navsari', name: 'Navsari', state: 'Gujarat', country: 'India', lat: 20.9500, lng: 72.9300, tz: 5.5, nameHi: 'नवसारी' },
  { id: 'okha', name: 'Okha', state: 'Gujarat', country: 'India', lat: 22.4635, lng: 69.0715, tz: 5.5, nameHi: 'ओखा' },
  { id: 'palanpur', name: 'Palanpur', state: 'Gujarat', country: 'India', lat: 24.1724, lng: 72.4346, tz: 5.5, nameHi: 'पालनपुर' },
  { id: 'patan', name: 'Patan', state: 'Gujarat', country: 'India', lat: 23.8493, lng: 72.1266, tz: 5.5, nameHi: 'पाटन' },
  { id: 'porbandar', name: 'Porbandar', state: 'Gujarat', country: 'India', lat: 21.6417, lng: 69.6293, tz: 5.5, nameHi: 'पोरबंदर' },
  { id: 'rajkot', name: 'Rajkot', state: 'Gujarat', country: 'India', lat: 22.3039, lng: 70.8022, tz: 5.5, nameHi: 'राजकोट' },
  { id: 'surat', name: 'Surat', state: 'Gujarat', country: 'India', lat: 21.1702, lng: 72.8311, tz: 5.5, nameHi: 'सूरत', isPopular: true },
  { id: 'surendranagar', name: 'Surendranagar', state: 'Gujarat', country: 'India', lat: 22.7284, lng: 71.6371, tz: 5.5, nameHi: 'सुरेन्द्रनगर' },
  { id: 'valsad', name: 'Valsad', state: 'Gujarat', country: 'India', lat: 20.5992, lng: 72.9342, tz: 5.5, nameHi: 'वलसाड' },
  { id: 'veraval', name: 'Veraval', state: 'Gujarat', country: 'India', lat: 20.9077, lng: 70.3677, tz: 5.5, nameHi: 'वेरावल (सोमनाथ)' },

  // --- HARYANA ---
  { id: 'ambala', name: 'Ambala', state: 'Haryana', country: 'India', lat: 30.3782, lng: 76.7767, tz: 5.5, nameHi: 'अम्बाला' },
  { id: 'bhiwani', name: 'Bhiwani', state: 'Haryana', country: 'India', lat: 28.7932, lng: 76.1390, tz: 5.5, nameHi: 'भिवानी' },
  { id: 'faridabad', name: 'Faridabad', state: 'Haryana', country: 'India', lat: 28.4089, lng: 77.3178, tz: 5.5, nameHi: 'फरीदाबाद' },
  { id: 'firozpur-jhirka', name: 'Firozpur Jhirka', state: 'Haryana', country: 'India', lat: 27.7925, lng: 76.9408, tz: 5.5, nameHi: 'फिरोजपुर झिरका' },
  { id: 'gurugram', name: 'Gurugram', state: 'Haryana', country: 'India', lat: 28.4595, lng: 77.0266, tz: 5.5, nameHi: 'गुरुग्राम', isPopular: true },
  { id: 'hansi', name: 'Hansi', state: 'Haryana', country: 'India', lat: 29.1022, lng: 75.9629, tz: 5.5, nameHi: 'हांसी' },
  { id: 'hisar', name: 'Hisar', state: 'Haryana', country: 'India', lat: 29.1492, lng: 75.7217, tz: 5.5, nameHi: 'हिसार' },
  { id: 'jind', name: 'Jind', state: 'Haryana', country: 'India', lat: 29.3157, lng: 76.3154, tz: 5.5, nameHi: 'जींद' },
  { id: 'kaithal', name: 'Kaithal', state: 'Haryana', country: 'India', lat: 29.8015, lng: 76.3996, tz: 5.5, nameHi: 'कैथल' },
  { id: 'karnal', name: 'Karnal', state: 'Haryana', country: 'India', lat: 29.6857, lng: 76.9905, tz: 5.5, nameHi: 'करनाल' },
  { id: 'kurukshetra', name: 'Kurukshetra', state: 'Haryana', country: 'India', lat: 29.9695, lng: 76.8783, tz: 5.5, nameHi: 'कुरुक्षेत्र', isPopular: true },
  { id: 'panipat', name: 'Panipat', state: 'Haryana', country: 'India', lat: 29.3909, lng: 76.9635, tz: 5.5, nameHi: 'पानीपत' },
  { id: 'pehowa', name: 'Pehowa', state: 'Haryana', country: 'India', lat: 29.9806, lng: 76.5817, tz: 5.5, nameHi: 'पेहोवा' },
  { id: 'rewari', name: 'Rewari', state: 'Haryana', country: 'India', lat: 28.1920, lng: 76.6186, tz: 5.5, nameHi: 'रेवाड़ी' },
  { id: 'rohtak', name: 'Rohtak', state: 'Haryana', country: 'India', lat: 28.8955, lng: 76.6066, tz: 5.5, nameHi: 'रोहतक' },
  { id: 'sirsa', name: 'Sirsa', state: 'Haryana', country: 'India', lat: 29.5349, lng: 75.0298, tz: 5.5, nameHi: 'सिरसा' },
  { id: 'sonipat', name: 'Sonipat', state: 'Haryana', country: 'India', lat: 28.9931, lng: 77.0151, tz: 5.5, nameHi: 'सोनीपत' },

  // --- HIMACHAL PRADESH ---
  { id: 'bilaspur-hp', name: 'Bilaspur', state: 'Himachal Pradesh', country: 'India', lat: 31.3458, lng: 76.7587, tz: 5.5, nameHi: 'बिलासपुर (हि.प्र.)' },
  { id: 'chamba', name: 'Chamba', state: 'Himachal Pradesh', country: 'India', lat: 32.5534, lng: 76.1258, tz: 5.5, nameHi: 'चंबा' },
  { id: 'dalhousie', name: 'Dalhousie', state: 'Himachal Pradesh', country: 'India', lat: 32.5387, lng: 75.9710, tz: 5.5, nameHi: 'डलहौजी' },
  { id: 'dharmshala', name: 'Dharmshala', state: 'Himachal Pradesh', country: 'India', lat: 32.2190, lng: 76.3234, tz: 5.5, nameHi: 'धर्मशाला' },
  { id: 'hamirpur-hp', name: 'Hamirpur', state: 'Himachal Pradesh', country: 'India', lat: 31.6862, lng: 76.5213, tz: 5.5, nameHi: 'हमीरपुर' },
  { id: 'kangra', name: 'Kangra', state: 'Himachal Pradesh', country: 'India', lat: 32.0998, lng: 76.2691, tz: 5.5, nameHi: 'कांगड़ा' },
  { id: 'kullu', name: 'Kullu', state: 'Himachal Pradesh', country: 'India', lat: 31.9579, lng: 77.1095, tz: 5.5, nameHi: 'कुल्लू' },
  { id: 'mandi', name: 'Mandi', state: 'Himachal Pradesh', country: 'India', lat: 31.7087, lng: 76.9320, tz: 5.5, nameHi: 'मंडी' },
  { id: 'nahan', name: 'Nahan', state: 'Himachal Pradesh', country: 'India', lat: 30.5599, lng: 77.2955, tz: 5.5, nameHi: 'नाहन' },
  { id: 'shimla', name: 'Shimla', state: 'Himachal Pradesh', country: 'India', lat: 31.1048, lng: 77.1734, tz: 5.5, nameHi: 'शिमला', isPopular: true },
  { id: 'una', name: 'Una', state: 'Himachal Pradesh', country: 'India', lat: 31.4685, lng: 76.2708, tz: 5.5, nameHi: 'ऊना' },

  // --- JAMMU AND KASHMIR ---
  { id: 'anantnag', name: 'Anantnag', state: 'Jammu and Kashmir', country: 'India', lat: 33.7311, lng: 75.1522, tz: 5.5, nameHi: 'अनंतनाग' },
  { id: 'baramula', name: 'Baramula', state: 'Jammu and Kashmir', country: 'India', lat: 34.2096, lng: 74.3436, tz: 5.5, nameHi: 'बारामूला' },
  { id: 'doda', name: 'Doda', state: 'Jammu and Kashmir', country: 'India', lat: 33.1450, lng: 75.5463, tz: 5.5, nameHi: 'डोडा' },
  { id: 'gulmarg', name: 'Gulmarg', state: 'Jammu and Kashmir', country: 'India', lat: 34.0484, lng: 74.3805, tz: 5.5, nameHi: 'गुलमर्ग' },
  { id: 'jammu', name: 'Jammu', state: 'Jammu and Kashmir', country: 'India', lat: 32.7266, lng: 74.8570, tz: 5.5, nameHi: 'जम्मू', isPopular: true },
  { id: 'kathua', name: 'Kathua', state: 'Jammu and Kashmir', country: 'India', lat: 32.3725, lng: 75.5190, tz: 5.5, nameHi: 'कठुआ' },
  { id: 'punch', name: 'Punch', state: 'Jammu and Kashmir', country: 'India', lat: 33.7711, lng: 74.0933, tz: 5.5, nameHi: 'पुंछ' },
  { id: 'rajouri', name: 'Rajouri', state: 'Jammu and Kashmir', country: 'India', lat: 33.3813, lng: 74.3142, tz: 5.5, nameHi: 'राजौरी' },
  { id: 'srinagar', name: 'Srinagar', state: 'Jammu and Kashmir', country: 'India', lat: 34.0837, lng: 74.7973, tz: 5.5, nameHi: 'श्रीनगर', isPopular: true },
  { id: 'udhampur', name: 'Udhampur', state: 'Jammu and Kashmir', country: 'India', lat: 32.9264, lng: 75.0062, tz: 5.5, nameHi: 'उधमपुर' },

  // --- JHARKHAND ---
  { id: 'bokaro', name: 'Bokaro', state: 'Jharkhand', country: 'India', lat: 23.6693, lng: 86.1511, tz: 5.5, nameHi: 'बोकारो', isPopular: true },
  { id: 'chaibasa', name: 'Chaibasa', state: 'Jharkhand', country: 'India', lat: 22.5538, lng: 85.8078, tz: 5.5, nameHi: 'चाईबासा' },
  { id: 'deoghar', name: 'Deoghar', state: 'Jharkhand', country: 'India', lat: 24.4826, lng: 86.7001, tz: 5.5, nameHi: 'देवघर (बाबा बैद्यनाथ)', isPopular: true },
  { id: 'dhanbad', name: 'Dhanbad', state: 'Jharkhand', country: 'India', lat: 23.7957, lng: 86.4304, tz: 5.5, nameHi: 'धनबाद', isPopular: true },
  { id: 'dumka', name: 'Dumka', state: 'Jharkhand', country: 'India', lat: 24.2678, lng: 87.2486, tz: 5.5, nameHi: 'दुमका (बासुकीनाथ)' },
  { id: 'giridih', name: 'Giridih', state: 'Jharkhand', country: 'India', lat: 24.1856, lng: 86.3075, tz: 5.5, nameHi: 'गिरिडीह' },
  { id: 'hazaribag', name: 'Hazaribag', state: 'Jharkhand', country: 'India', lat: 23.9937, lng: 85.3623, tz: 5.5, nameHi: 'हजारीबाग' },
  { id: 'jamshedpur', name: 'Jamshedpur', state: 'Jharkhand', country: 'India', lat: 22.8046, lng: 86.2029, tz: 5.5, nameHi: 'जमशेदपुर (टाटानगर)', isPopular: true },
  { id: 'jharia', name: 'Jharia', state: 'Jharkhand', country: 'India', lat: 23.7418, lng: 86.4172, tz: 5.5, nameHi: 'झरिया' },
  { id: 'rajmahal', name: 'Rajmahal', state: 'Jharkhand', country: 'India', lat: 25.0500, lng: 87.8333, tz: 5.5, nameHi: 'राजमहल' },
  { id: 'ranchi', name: 'Ranchi', state: 'Jharkhand', country: 'India', lat: 23.3441, lng: 85.3096, tz: 5.5, nameHi: 'राँची', isPopular: true },
  { id: 'saraikela', name: 'Saraikela', state: 'Jharkhand', country: 'India', lat: 22.6983, lng: 85.9326, tz: 5.5, nameHi: 'सरायकेला' },

  // --- KARNATAKA ---
  { id: 'badami', name: 'Badami', state: 'Karnataka', country: 'India', lat: 15.9187, lng: 75.6766, tz: 5.5, nameHi: 'बादामी' },
  { id: 'ballari', name: 'Ballari', state: 'Karnataka', country: 'India', lat: 15.1394, lng: 76.9214, tz: 5.5, nameHi: 'बल्लारी (बेल्लारी)' },
  { id: 'bengaluru', name: 'Bengaluru', state: 'Karnataka', country: 'India', lat: 12.9716, lng: 77.5946, tz: 5.5, nameHi: 'बेंगलुरु', isPopular: true },
  { id: 'belagavi', name: 'Belagavi', state: 'Karnataka', country: 'India', lat: 15.8497, lng: 74.4977, tz: 5.5, nameHi: 'बेलगावी' },
  { id: 'bhadravati', name: 'Bhadravati', state: 'Karnataka', country: 'India', lat: 13.8474, lng: 75.7042, tz: 5.5, nameHi: 'भद्रावती' },
  { id: 'bidar', name: 'Bidar', state: 'Karnataka', country: 'India', lat: 17.9104, lng: 77.5199, tz: 5.5, nameHi: 'बीदर' },
  { id: 'chikkamagaluru', name: 'Chikkamagaluru', state: 'Karnataka', country: 'India', lat: 13.3161, lng: 75.7720, tz: 5.5, nameHi: 'चिकमगलूर' },
  { id: 'chitradurga', name: 'Chitradurga', state: 'Karnataka', country: 'India', lat: 14.2251, lng: 76.3980, tz: 5.5, nameHi: 'चित्रदुर्ग' },
  { id: 'davangere', name: 'Davangere', state: 'Karnataka', country: 'India', lat: 14.4644, lng: 75.9218, tz: 5.5, nameHi: 'दावणगेरे' },
  { id: 'halebid', name: 'Halebid', state: 'Karnataka', country: 'India', lat: 13.2167, lng: 75.9897, tz: 5.5, nameHi: 'हलेबिड' },
  { id: 'hassan', name: 'Hassan', state: 'Karnataka', country: 'India', lat: 13.0072, lng: 76.1030, tz: 5.5, nameHi: 'हासन' },
  { id: 'hubballi-dharwad', name: 'Hubballi-Dharwad', state: 'Karnataka', country: 'India', lat: 15.3647, lng: 75.1240, tz: 5.5, nameHi: 'हुबली-धारवाड़' },
  { id: 'kalaburagi', name: 'Kalaburagi', state: 'Karnataka', country: 'India', lat: 17.3297, lng: 76.8343, tz: 5.5, nameHi: 'कलबुर्गी (गुलबर्गा)' },
  { id: 'kolar', name: 'Kolar', state: 'Karnataka', country: 'India', lat: 13.1367, lng: 78.1292, tz: 5.5, nameHi: 'कोलार' },
  { id: 'madikeri', name: 'Madikeri', state: 'Karnataka', country: 'India', lat: 12.4244, lng: 75.7382, tz: 5.5, nameHi: 'मडिकेरी (कूर्ग)' },
  { id: 'mandya', name: 'Mandya', state: 'Karnataka', country: 'India', lat: 12.5218, lng: 76.8951, tz: 5.5, nameHi: 'मांड्या' },
  { id: 'mangaluru', name: 'Mangaluru', state: 'Karnataka', country: 'India', lat: 12.9141, lng: 74.8560, tz: 5.5, nameHi: 'मंगलुरु', isPopular: true },
  { id: 'mysuru', name: 'Mysuru', state: 'Karnataka', country: 'India', lat: 12.2958, lng: 76.6394, tz: 5.5, nameHi: 'मैसूरु', isPopular: true },
  { id: 'raichur', name: 'Raichur', state: 'Karnataka', country: 'India', lat: 16.2076, lng: 77.3463, tz: 5.5, nameHi: 'रायचूर' },
  { id: 'shivamogga', name: 'Shivamogga', state: 'Karnataka', country: 'India', lat: 13.9299, lng: 75.5681, tz: 5.5, nameHi: 'शिवमोग्गा' },
  { id: 'shravanabelagola', name: 'Shravanabelagola', state: 'Karnataka', country: 'India', lat: 12.8580, lng: 76.4860, tz: 5.5, nameHi: 'श्रवणबेलगोला' },
  { id: 'shrirangapattana', name: 'Shrirangapattana', state: 'Karnataka', country: 'India', lat: 12.4223, lng: 76.6946, tz: 5.5, nameHi: 'श्रीरंगपट्टण' },
  { id: 'tumakuru', name: 'Tumakuru', state: 'Karnataka', country: 'India', lat: 13.3409, lng: 77.1010, tz: 5.5, nameHi: 'तुमकुरु' },
  { id: 'vijayapura', name: 'Vijayapura', state: 'Karnataka', country: 'India', lat: 16.8302, lng: 75.7100, tz: 5.5, nameHi: 'विजयपुरा (बीजापुर)' },

  // --- KERALA ---
  { id: 'alappuzha', name: 'Alappuzha', state: 'Kerala', country: 'India', lat: 9.4981, lng: 76.3388, tz: 5.5, nameHi: 'अलप्पुझा (अलेप्पी)' },
  { id: 'vatakara', name: 'Vatakara', state: 'Kerala', country: 'India', lat: 11.6089, lng: 75.5917, tz: 5.5, nameHi: 'वडकरा' },
  { id: 'idukki', name: 'Idukki', state: 'Kerala', country: 'India', lat: 9.8497, lng: 76.9806, tz: 5.5, nameHi: 'इडुक्की' },
  { id: 'kannur', name: 'Kannur', state: 'Kerala', country: 'India', lat: 11.8745, lng: 75.3704, tz: 5.5, nameHi: 'कन्नूर' },
  { id: 'kochi', name: 'Kochi', state: 'Kerala', country: 'India', lat: 9.9312, lng: 76.2673, tz: 5.5, nameHi: 'कोच्चि (कोचीन)', isPopular: true },
  { id: 'kollam', name: 'Kollam', state: 'Kerala', country: 'India', lat: 8.8932, lng: 76.6141, tz: 5.5, nameHi: 'कोल्लम' },
  { id: 'kottayam', name: 'Kottayam', state: 'Kerala', country: 'India', lat: 9.5916, lng: 76.5222, tz: 5.5, nameHi: 'कोट्टायम' },
  { id: 'kozhikode', name: 'Kozhikode', state: 'Kerala', country: 'India', lat: 11.2588, lng: 75.7804, tz: 5.5, nameHi: 'कोझिकोड (कालिकट)' },
  { id: 'mattancheri', name: 'Mattancheri', state: 'Kerala', country: 'India', lat: 9.9577, lng: 76.2571, tz: 5.5, nameHi: 'मट्टनचेरी' },
  { id: 'palakkad', name: 'Palakkad', state: 'Kerala', country: 'India', lat: 10.7867, lng: 76.6548, tz: 5.5, nameHi: 'पालक्काड़' },
  { id: 'thalassery', name: 'Thalassery', state: 'Kerala', country: 'India', lat: 11.7491, lng: 75.4890, tz: 5.5, nameHi: 'थलस्सेरी' },
  { id: 'thiruvananthapuram', name: 'Thiruvananthapuram', state: 'Kerala', country: 'India', lat: 8.5241, lng: 76.9366, tz: 5.5, nameHi: 'तिरुवनंतपुरम', isPopular: true },
  { id: 'thrissur', name: 'Thrissur', state: 'Kerala', country: 'India', lat: 10.5276, lng: 76.2144, tz: 5.5, nameHi: 'त्रिशूर (वडक्कुम्नाथन)' },

  // --- LADAKH ---
  { id: 'kargil', name: 'Kargil', state: 'Ladakh', country: 'India', lat: 34.5539, lng: 76.1349, tz: 5.5, nameHi: 'कारगिल' },
  { id: 'leh', name: 'Leh', state: 'Ladakh', country: 'India', lat: 34.1526, lng: 77.5771, tz: 5.5, nameHi: 'लेह' },

  // --- MADHYA PRADESH ---
  { id: 'balaghat', name: 'Balaghat', state: 'Madhya Pradesh', country: 'India', lat: 21.8129, lng: 80.1837, tz: 5.5, nameHi: 'बालाघाट' },
  { id: 'barwani', name: 'Barwani', state: 'Madhya Pradesh', country: 'India', lat: 22.0366, lng: 74.9032, tz: 5.5, nameHi: 'बड़वानी' },
  { id: 'betul', name: 'Betul', state: 'Madhya Pradesh', country: 'India', lat: 21.9015, lng: 77.9018, tz: 5.5, nameHi: 'बैतूल' },
  { id: 'bharhut', name: 'Bharhut', state: 'Madhya Pradesh', country: 'India', lat: 24.4797, lng: 80.8732, tz: 5.5, nameHi: 'भरहुत' },
  { id: 'bhind', name: 'Bhind', state: 'Madhya Pradesh', country: 'India', lat: 26.5647, lng: 78.7842, tz: 5.5, nameHi: 'भिंड' },
  { id: 'bhojpur', name: 'Bhojpur', state: 'Madhya Pradesh', country: 'India', lat: 23.1000, lng: 77.5833, tz: 5.5, nameHi: 'भोजपुर (शिव मन्दिर)' },
  { id: 'bhopal', name: 'Bhopal', state: 'Madhya Pradesh', country: 'India', lat: 23.2599, lng: 77.4126, tz: 5.5, nameHi: 'भोपाल', isPopular: true },
  { id: 'burhanpur', name: 'Burhanpur', state: 'Madhya Pradesh', country: 'India', lat: 21.3109, lng: 76.2299, tz: 5.5, nameHi: 'बुरहानपुर' },
  { id: 'chhatarpur', name: 'Chhatarpur', state: 'Madhya Pradesh', country: 'India', lat: 24.9164, lng: 79.5811, tz: 5.5, nameHi: 'छतरपुर' },
  { id: 'chhindwara', name: 'Chhindwara', state: 'Madhya Pradesh', country: 'India', lat: 22.0574, lng: 78.9382, tz: 5.5, nameHi: 'छिंदवाड़ा' },
  { id: 'damoh', name: 'Damoh', state: 'Madhya Pradesh', country: 'India', lat: 23.8323, lng: 79.4422, tz: 5.5, nameHi: 'दमोह' },
  { id: 'datia', name: 'Datia', state: 'Madhya Pradesh', country: 'India', lat: 25.6685, lng: 78.4604, tz: 5.5, nameHi: 'दतिया (पीताम्बरा पीठ)' },
  { id: 'dewas', name: 'Dewas', state: 'Madhya Pradesh', country: 'India', lat: 22.9676, lng: 76.0534, tz: 5.5, nameHi: 'देवास' },
  { id: 'dhar', name: 'Dhar', state: 'Madhya Pradesh', country: 'India', lat: 22.5982, lng: 75.2974, tz: 5.5, nameHi: 'धार' },
  { id: 'mhow', name: 'Dr. Ambedkar Nagar (Mhow)', state: 'Madhya Pradesh', country: 'India', lat: 22.5537, lng: 75.7548, tz: 5.5, nameHi: 'महू' },
  { id: 'guna', name: 'Guna', state: 'Madhya Pradesh', country: 'India', lat: 24.6469, lng: 77.3110, tz: 5.5, nameHi: 'गुना' },
  { id: 'gwalior', name: 'Gwalior', state: 'Madhya Pradesh', country: 'India', lat: 26.2183, lng: 78.1828, tz: 5.5, nameHi: 'ग्वालियर', isPopular: true },
  { id: 'hoshangabad', name: 'Hoshangabad', state: 'Madhya Pradesh', country: 'India', lat: 22.7519, lng: 77.7289, tz: 5.5, nameHi: 'नर्मदापुरम (होशंगाबाद)' },
  { id: 'indore', name: 'Indore', state: 'Madhya Pradesh', country: 'India', lat: 22.7196, lng: 75.8577, tz: 5.5, nameHi: 'इन्दौर', isPopular: true },
  { id: 'itarsi', name: 'Itarsi', state: 'Madhya Pradesh', country: 'India', lat: 22.6124, lng: 77.7610, tz: 5.5, nameHi: 'इटारसी' },
  { id: 'jabalpur', name: 'Jabalpur', state: 'Madhya Pradesh', country: 'India', lat: 23.1815, lng: 79.9864, tz: 5.5, nameHi: 'जबलपुर (भेड़ाघाट)' },
  { id: 'jhabua', name: 'Jhabua', state: 'Madhya Pradesh', country: 'India', lat: 22.7694, lng: 74.5947, tz: 5.5, nameHi: 'झाबुआ' },
  { id: 'khajuraho', name: 'Khajuraho', state: 'Madhya Pradesh', country: 'India', lat: 24.8318, lng: 79.9199, tz: 5.5, nameHi: 'खजुराहो', isPopular: true },
  { id: 'khandwa', name: 'Khandwa', state: 'Madhya Pradesh', country: 'India', lat: 21.8314, lng: 76.3498, tz: 5.5, nameHi: 'खंडवा (ओंकारेश्वर)' },
  { id: 'khargone', name: 'Khargone', state: 'Madhya Pradesh', country: 'India', lat: 21.8242, lng: 75.6111, tz: 5.5, nameHi: 'खरगोन' },
  { id: 'maheshwar', name: 'Maheshwar', state: 'Madhya Pradesh', country: 'India', lat: 22.1764, lng: 75.5866, tz: 5.5, nameHi: 'महेश्वर' },
  { id: 'mandla', name: 'Mandla', state: 'Madhya Pradesh', country: 'India', lat: 22.5986, lng: 80.3712, tz: 5.5, nameHi: 'मंडला' },
  { id: 'mandsaur', name: 'Mandsaur', state: 'Madhya Pradesh', country: 'India', lat: 24.0722, lng: 75.0683, tz: 5.5, nameHi: 'मंदसौर (पशुपतिनाथ)' },
  { id: 'morena', name: 'Morena', state: 'Madhya Pradesh', country: 'India', lat: 26.4950, lng: 77.9940, tz: 5.5, nameHi: 'मुरैना' },
  { id: 'murwara', name: 'Murwara', state: 'Madhya Pradesh', country: 'India', lat: 23.8343, lng: 80.3992, tz: 5.5, nameHi: 'कटनी (मुरवारा)' },
  { id: 'narsimhapur', name: 'Narsimhapur', state: 'Madhya Pradesh', country: 'India', lat: 22.9430, lng: 79.1970, tz: 5.5, nameHi: 'नरसिंहपुर' },
  { id: 'narsinghgarh', name: 'Narsinghgarh', state: 'Madhya Pradesh', country: 'India', lat: 23.7061, lng: 77.0894, tz: 5.5, nameHi: 'नरसिंहगढ़' },
  { id: 'narwar', name: 'Narwar', state: 'Madhya Pradesh', country: 'India', lat: 25.6497, lng: 77.9042, tz: 5.5, nameHi: 'नरवर' },
  { id: 'neemuch', name: 'Neemuch', state: 'Madhya Pradesh', country: 'India', lat: 24.4647, lng: 74.8697, tz: 5.5, nameHi: 'नीमच' },
  { id: 'nowgong', name: 'Nowgong', state: 'Madhya Pradesh', country: 'India', lat: 25.0560, lng: 79.4437, tz: 5.5, nameHi: 'नौगांव' },
  { id: 'orchha', name: 'Orchha', state: 'Madhya Pradesh', country: 'India', lat: 25.3516, lng: 78.6433, tz: 5.5, nameHi: 'ओरछा (रामराजा मन्दिर)', isPopular: true },
  { id: 'panna', name: 'Panna', state: 'Madhya Pradesh', country: 'India', lat: 24.7208, lng: 80.1837, tz: 5.5, nameHi: 'पन्ना' },
  { id: 'raisen', name: 'Raisen', state: 'Madhya Pradesh', country: 'India', lat: 23.3315, lng: 77.7818, tz: 5.5, nameHi: 'रायसेन (सांची)' },
  { id: 'rajgarh', name: 'Rajgarh', state: 'Madhya Pradesh', country: 'India', lat: 24.0083, lng: 76.7289, tz: 5.5, nameHi: 'राजगढ़' },
  { id: 'ratlam', name: 'Ratlam', state: 'Madhya Pradesh', country: 'India', lat: 23.3315, lng: 75.0367, tz: 5.5, nameHi: 'रतलाम' },
  { id: 'rewa', name: 'Rewa', state: 'Madhya Pradesh', country: 'India', lat: 24.5362, lng: 81.3037, tz: 5.5, nameHi: 'रीवा' },
  { id: 'sagar', name: 'Sagar', state: 'Madhya Pradesh', country: 'India', lat: 23.8388, lng: 78.7378, tz: 5.5, nameHi: 'सागर' },
  { id: 'sarangpur', name: 'Sarangpur', state: 'Madhya Pradesh', country: 'India', lat: 23.5683, lng: 76.4678, tz: 5.5, nameHi: 'सारंगपुर' },
  { id: 'satna', name: 'Satna', state: 'Madhya Pradesh', country: 'India', lat: 24.6005, lng: 80.8322, tz: 5.5, nameHi: 'सतना (मैहर)' },
  { id: 'sehore', name: 'Sehore', state: 'Madhya Pradesh', country: 'India', lat: 23.2030, lng: 77.0844, tz: 5.5, nameHi: 'सीहोर' },
  { id: 'seoni', name: 'Seoni', state: 'Madhya Pradesh', country: 'India', lat: 22.0869, lng: 79.5435, tz: 5.5, nameHi: 'सिवनी' },
  { id: 'shahdol', name: 'Shahdol', state: 'Madhya Pradesh', country: 'India', lat: 23.2856, lng: 81.3537, tz: 5.5, nameHi: 'शहडोल' },
  { id: 'shajapur', name: 'Shajapur', state: 'Madhya Pradesh', country: 'India', lat: 23.4274, lng: 76.2770, tz: 5.5, nameHi: 'शाजापुर' },
  { id: 'sheopur', name: 'Sheopur', state: 'Madhya Pradesh', country: 'India', lat: 25.6669, lng: 76.6961, tz: 5.5, nameHi: 'श्योपुर' },
  { id: 'shivpuri', name: 'Shivpuri', state: 'Madhya Pradesh', country: 'India', lat: 25.4244, lng: 77.6586, tz: 5.5, nameHi: 'शिवपुरी' },
  { id: 'ujjain', name: 'Ujjain', state: 'Madhya Pradesh', country: 'India', lat: 23.1765, lng: 75.7885, tz: 5.5, nameHi: 'उज्जैन (महाकालेश्वर)', isPopular: true },
  { id: 'vidisha', name: 'Vidisha', state: 'Madhya Pradesh', country: 'India', lat: 23.5251, lng: 77.8081, tz: 5.5, nameHi: 'विदिशा' },

  // --- MAHARASHTRA ---
  { id: 'ahmadnagar', name: 'Ahmadnagar', state: 'Maharashtra', country: 'India', lat: 19.0952, lng: 74.7496, tz: 5.5, nameHi: 'अहमदनगर (अहिल्यानगर)' },
  { id: 'akola', name: 'Akola', state: 'Maharashtra', country: 'India', lat: 20.7002, lng: 77.0082, tz: 5.5, nameHi: 'अकोला' },
  { id: 'amravati', name: 'Amravati', state: 'Maharashtra', country: 'India', lat: 20.9374, lng: 77.7796, tz: 5.5, nameHi: 'अमरावती' },
  { id: 'aurangabad', name: 'Aurangabad', state: 'Maharashtra', country: 'India', lat: 19.8762, lng: 75.3433, tz: 5.5, nameHi: 'छत्रपति संभाजीनगर (घृष्णेश्वर)', isPopular: true },
  { id: 'bhandara', name: 'Bhandara', state: 'Maharashtra', country: 'India', lat: 21.1683, lng: 79.6548, tz: 5.5, nameHi: 'भंडारा' },
  { id: 'bhusawal', name: 'Bhusawal', state: 'Maharashtra', country: 'India', lat: 21.0455, lng: 75.7885, tz: 5.5, nameHi: 'भुसावल' },
  { id: 'bid', name: 'Bid', state: 'Maharashtra', country: 'India', lat: 18.9891, lng: 75.7601, tz: 5.5, nameHi: 'बीड' },
  { id: 'buldhana', name: 'Buldhana', state: 'Maharashtra', country: 'India', lat: 20.5317, lng: 76.1825, tz: 5.5, nameHi: 'बुलढाणा' },
  { id: 'chandrapur', name: 'Chandrapur', state: 'Maharashtra', country: 'India', lat: 19.9615, lng: 79.2961, tz: 5.5, nameHi: 'चंद्रपुर' },
  { id: 'daulatabad', name: 'Daulatabad', state: 'Maharashtra', country: 'India', lat: 19.9427, lng: 75.2131, tz: 5.5, nameHi: 'दौलताबाद' },
  { id: 'dhule', name: 'Dhule', state: 'Maharashtra', country: 'India', lat: 20.9042, lng: 74.7749, tz: 5.5, nameHi: 'धुले' },
  { id: 'jalgaon', name: 'Jalgaon', state: 'Maharashtra', country: 'India', lat: 21.0077, lng: 75.5626, tz: 5.5, nameHi: 'जलगांव' },
  { id: 'kalyan', name: 'Kalyan', state: 'Maharashtra', country: 'India', lat: 19.2403, lng: 73.1305, tz: 5.5, nameHi: 'कल्याण' },
  { id: 'karli', name: 'Karli', state: 'Maharashtra', country: 'India', lat: 18.7833, lng: 73.4833, tz: 5.5, nameHi: 'कार्ला' },
  { id: 'kolhapur', name: 'Kolhapur', state: 'Maharashtra', country: 'India', lat: 16.7050, lng: 74.2433, tz: 5.5, nameHi: 'कोल्हापुर (महालक्ष्मी)', isPopular: true },
  { id: 'mahabaleshwar', name: 'Mahabaleshwar', state: 'Maharashtra', country: 'India', lat: 17.9307, lng: 73.6477, tz: 5.5, nameHi: 'महाबलेश्वर' },
  { id: 'malegaon', name: 'Malegaon', state: 'Maharashtra', country: 'India', lat: 20.5579, lng: 74.5287, tz: 5.5, nameHi: 'मालेगांव' },
  { id: 'matheran', name: 'Matheran', state: 'Maharashtra', country: 'India', lat: 18.9865, lng: 73.2679, tz: 5.5, nameHi: 'माथेरान' },
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', country: 'India', lat: 19.0760, lng: 72.8777, tz: 5.5, nameHi: 'मुम्बई (सिद्धिविनायक)', isPopular: true },
  { id: 'nagpur', name: 'Nagpur', state: 'Maharashtra', country: 'India', lat: 21.1458, lng: 79.0882, tz: 5.5, nameHi: 'नागपुर', isPopular: true },
  { id: 'nanded', name: 'Nanded', state: 'Maharashtra', country: 'India', lat: 19.1383, lng: 77.3210, tz: 5.5, nameHi: 'नांदेड़ (हजूर साहिब)' },
  { id: 'nashik', name: 'Nashik', state: 'Maharashtra', country: 'India', lat: 19.9975, lng: 73.7898, tz: 5.5, nameHi: 'नासिक (त्र्यम्बकेश्वर)', isPopular: true },
  { id: 'osmanabad', name: 'Osmanabad', state: 'Maharashtra', country: 'India', lat: 18.1856, lng: 76.0418, tz: 5.5, nameHi: 'धाराशिव (उस्मानाबाद)' },
  { id: 'pandharpur', name: 'Pandharpur', state: 'Maharashtra', country: 'India', lat: 17.6775, lng: 75.3283, tz: 5.5, nameHi: 'पंढरपुर (विठोबा)', isPopular: true },
  { id: 'parbhani', name: 'Parbhani', state: 'Maharashtra', country: 'India', lat: 19.2644, lng: 76.7767, tz: 5.5, nameHi: 'परभणी' },
  { id: 'pune', name: 'Pune', state: 'Maharashtra', country: 'India', lat: 18.5204, lng: 73.8567, tz: 5.5, nameHi: 'पुणे (दगडूशेठ)', isPopular: true },
  { id: 'ratnagiri', name: 'Ratnagiri', state: 'Maharashtra', country: 'India', lat: 16.9902, lng: 73.3120, tz: 5.5, nameHi: 'रत्नागिरि' },
  { id: 'sangli', name: 'Sangli', state: 'Maharashtra', country: 'India', lat: 16.8524, lng: 74.5815, tz: 5.5, nameHi: 'सांगली' },
  { id: 'satara', name: 'Satara', state: 'Maharashtra', country: 'India', lat: 17.6805, lng: 73.9934, tz: 5.5, nameHi: 'सतारा' },
  { id: 'sevagram', name: 'Sevagram', state: 'Maharashtra', country: 'India', lat: 20.7186, lng: 78.6144, tz: 5.5, nameHi: 'सेवाग्राम' },
  { id: 'solapur', name: 'Solapur', state: 'Maharashtra', country: 'India', lat: 17.6599, lng: 75.9064, tz: 5.5, nameHi: 'सोलापुर' },
  { id: 'thane', name: 'Thane', state: 'Maharashtra', country: 'India', lat: 19.2183, lng: 72.9781, tz: 5.5, nameHi: 'ठाणे' },
  { id: 'ulhasnagar', name: 'Ulhasnagar', state: 'Maharashtra', country: 'India', lat: 19.2215, lng: 73.1645, tz: 5.5, nameHi: 'उल्हासनगर' },
  { id: 'vasai-virar', name: 'Vasai-Virar', state: 'Maharashtra', country: 'India', lat: 19.3919, lng: 72.8397, tz: 5.5, nameHi: 'वसई-विरार' },
  { id: 'wardha', name: 'Wardha', state: 'Maharashtra', country: 'India', lat: 20.7453, lng: 78.6022, tz: 5.5, nameHi: 'वर्धा' },
  { id: 'yavatmal', name: 'Yavatmal', state: 'Maharashtra', country: 'India', lat: 20.3888, lng: 78.1204, tz: 5.5, nameHi: 'यवतमाल' },

  // --- MANIPUR ---
  { id: 'imphal', name: 'Imphal', state: 'Manipur', country: 'India', lat: 24.8170, lng: 93.9368, tz: 5.5, nameHi: 'इम्फाल' },

  // --- MEGHALAYA ---
  { id: 'cherrapunji', name: 'Cherrapunji', state: 'Meghalaya', country: 'India', lat: 25.2702, lng: 91.7323, tz: 5.5, nameHi: 'चेरापूंजी (सोहरा)' },
  { id: 'shillong', name: 'Shillong', state: 'Meghalaya', country: 'India', lat: 25.5788, lng: 91.8933, tz: 5.5, nameHi: 'शिलांग', isPopular: true },

  // --- MIZORAM ---
  { id: 'aizawl', name: 'Aizawl', state: 'Mizoram', country: 'India', lat: 23.7271, lng: 92.7176, tz: 5.5, nameHi: 'आइजोल' },
  { id: 'lunglei', name: 'Lunglei', state: 'Mizoram', country: 'India', lat: 22.8876, lng: 92.7410, tz: 5.5, nameHi: 'लुंगलेई' },

  // --- NAGALAND ---
  { id: 'kohima', name: 'Kohima', state: 'Nagaland', country: 'India', lat: 25.6751, lng: 94.1086, tz: 5.5, nameHi: 'कोहिमा' },
  { id: 'mon', name: 'Mon', state: 'Nagaland', country: 'India', lat: 26.7461, lng: 95.0617, tz: 5.5, nameHi: 'मोन' },
  { id: 'phek', name: 'Phek', state: 'Nagaland', country: 'India', lat: 25.6833, lng: 94.5000, tz: 5.5, nameHi: 'फेक' },
  { id: 'wokha', name: 'Wokha', state: 'Nagaland', country: 'India', lat: 26.0988, lng: 94.2625, tz: 5.5, nameHi: 'वोखा' },
  { id: 'zunheboto', name: 'Zunheboto', state: 'Nagaland', country: 'India', lat: 25.9667, lng: 94.5167, tz: 5.5, nameHi: 'जुन्हेबोटो' },

  // --- ODISHA ---
  { id: 'balangir', name: 'Balangir', state: 'Odisha', country: 'India', lat: 20.7107, lng: 83.4862, tz: 5.5, nameHi: 'बलांगीर' },
  { id: 'baleshwar', name: 'Baleshwar', state: 'Odisha', country: 'India', lat: 21.4934, lng: 86.9135, tz: 5.5, nameHi: 'बालेश्वर' },
  { id: 'baripada', name: 'Baripada', state: 'Odisha', country: 'India', lat: 21.9346, lng: 86.7324, tz: 5.5, nameHi: 'बारीपदा' },
  { id: 'bhubaneshwar', name: 'Bhubaneshwar', state: 'Odisha', country: 'India', lat: 20.2961, lng: 85.8245, tz: 5.5, nameHi: 'भुवनेश्वर (लिंगराज)', isPopular: true },
  { id: 'brahmapur', name: 'Brahmapur', state: 'Odisha', country: 'India', lat: 19.3150, lng: 84.7941, tz: 5.5, nameHi: 'ब्रह्मपुर' },
  { id: 'cuttack', name: 'Cuttack', state: 'Odisha', country: 'India', lat: 20.4625, lng: 85.8828, tz: 5.5, nameHi: 'कटक (चंडी मन्दिर)' },
  { id: 'dhenkanal', name: 'Dhenkanal', state: 'Odisha', country: 'India', lat: 20.6657, lng: 85.5977, tz: 5.5, nameHi: 'ढेंकनाल' },
  { id: 'kendujhar', name: 'Kendujhar', state: 'Odisha', country: 'India', lat: 21.6289, lng: 85.5817, tz: 5.5, nameHi: 'केन्दुझर' },
  { id: 'konark', name: 'Konark', state: 'Odisha', country: 'India', lat: 19.8876, lng: 86.0945, tz: 5.5, nameHi: 'कोणार्क (सूर्य मन्दिर)', isPopular: true },
  { id: 'koraput', name: 'Koraput', state: 'Odisha', country: 'India', lat: 18.8135, lng: 82.7118, tz: 5.5, nameHi: 'कोरापुट' },
  { id: 'paradip', name: 'Paradip', state: 'Odisha', country: 'India', lat: 20.3165, lng: 86.6114, tz: 5.5, nameHi: 'पारादीप' },
  { id: 'phulabani', name: 'Phulabani', state: 'Odisha', country: 'India', lat: 20.4764, lng: 84.2323, tz: 5.5, nameHi: 'फुलबानी' },
  { id: 'puri', name: 'Puri', state: 'Odisha', country: 'India', lat: 19.8135, lng: 85.8312, tz: 5.5, nameHi: 'पुरी (श्री जगन्नाथ धाम)', isPopular: true },
  { id: 'sambalpur', name: 'Sambalpur', state: 'Odisha', country: 'India', lat: 21.4669, lng: 83.9812, tz: 5.5, nameHi: 'संबलपुर (समलेश्वरी)' },
  { id: 'udayagiri', name: 'Udayagiri', state: 'Odisha', country: 'India', lat: 20.1283, lng: 84.1436, tz: 5.5, nameHi: 'उदयगिरि' },

  // --- PUDUCHERRY ---
  { id: 'karaikal', name: 'Karaikal', state: 'Puducherry', country: 'India', lat: 10.9254, lng: 79.8380, tz: 5.5, nameHi: 'कराईकल' },
  { id: 'mahe', name: 'Mahe', state: 'Puducherry', country: 'India', lat: 11.7002, lng: 75.5340, tz: 5.5, nameHi: 'माहे' },
  { id: 'puducherry', name: 'Puducherry', state: 'Puducherry', country: 'India', lat: 11.9416, lng: 79.8083, tz: 5.5, nameHi: 'पुदुच्चेरी (पांडिचेरी)' },
  { id: 'yanam', name: 'Yanam', state: 'Puducherry', country: 'India', lat: 16.7333, lng: 82.2167, tz: 5.5, nameHi: 'यानम' },

  // --- PUNJAB ---
  { id: 'amritsar', name: 'Amritsar', state: 'Punjab', country: 'India', lat: 31.6340, lng: 74.8723, tz: 5.5, nameHi: 'अमृतसर (श्री हरिमंदिर साहिब)', isPopular: true },
  { id: 'batala', name: 'Batala', state: 'Punjab', country: 'India', lat: 31.8186, lng: 75.2028, tz: 5.5, nameHi: 'बटाला' },
  { id: 'faridkot', name: 'Faridkot', state: 'Punjab', country: 'India', lat: 30.6769, lng: 74.7583, tz: 5.5, nameHi: 'फरीदकोट' },
  { id: 'firozpur', name: 'Firozpur', state: 'Punjab', country: 'India', lat: 30.9237, lng: 74.6117, tz: 5.5, nameHi: 'फिरोजपुर' },
  { id: 'gurdaspur', name: 'Gurdaspur', state: 'Punjab', country: 'India', lat: 32.0419, lng: 75.4053, tz: 5.5, nameHi: 'गुरदासपुर' },
  { id: 'hoshiarpur', name: 'Hoshiarpur', state: 'Punjab', country: 'India', lat: 31.5273, lng: 75.9149, tz: 5.5, nameHi: 'होशियारपुर (भृगु संहिता)' },
  { id: 'jalandhar', name: 'Jalandhar', state: 'Punjab', country: 'India', lat: 31.3260, lng: 75.5762, tz: 5.5, nameHi: 'जालंधर' },
  { id: 'kapurthala', name: 'Kapurthala', state: 'Punjab', country: 'India', lat: 31.3800, lng: 75.3800, tz: 5.5, nameHi: 'कपूरथला' },
  { id: 'ludhiana', name: 'Ludhiana', state: 'Punjab', country: 'India', lat: 30.9010, lng: 75.8573, tz: 5.5, nameHi: 'लुधियाना', isPopular: true },
  { id: 'nabha', name: 'Nabha', state: 'Punjab', country: 'India', lat: 30.3747, lng: 76.1500, tz: 5.5, nameHi: 'नाभा' },
  { id: 'patiala', name: 'Patiala', state: 'Punjab', country: 'India', lat: 30.3398, lng: 76.3869, tz: 5.5, nameHi: 'पटियाला' },
  { id: 'rupnagar', name: 'Rupnagar', state: 'Punjab', country: 'India', lat: 30.9664, lng: 76.5331, tz: 5.5, nameHi: 'रूपनगर (रोपड़)' },
  { id: 'sangrur', name: 'Sangrur', state: 'Punjab', country: 'India', lat: 30.2458, lng: 75.8422, tz: 5.5, nameHi: 'संगरूर' },

  // --- RAJASTHAN ---
  { id: 'abu', name: 'Abu', state: 'Rajasthan', country: 'India', lat: 24.5925, lng: 72.7156, tz: 5.5, nameHi: 'माउंट आबू (देलवाड़ा)' },
  { id: 'ajmer', name: 'Ajmer', state: 'Rajasthan', country: 'India', lat: 26.4499, lng: 74.6399, tz: 5.5, nameHi: 'अजमेर' },
  { id: 'alwar', name: 'Alwar', state: 'Rajasthan', country: 'India', lat: 27.5530, lng: 76.6346, tz: 5.5, nameHi: 'अलवर' },
  { id: 'amer', name: 'Amer', state: 'Rajasthan', country: 'India', lat: 26.9855, lng: 75.8513, tz: 5.5, nameHi: 'आमेर' },
  { id: 'barmer', name: 'Barmer', state: 'Rajasthan', country: 'India', lat: 25.7521, lng: 71.4181, tz: 5.5, nameHi: 'बाड़मेर' },
  { id: 'beawar', name: 'Beawar', state: 'Rajasthan', country: 'India', lat: 26.1012, lng: 74.3197, tz: 5.5, nameHi: 'ब्यावर' },
  { id: 'bharatpur', name: 'Bharatpur', state: 'Rajasthan', country: 'India', lat: 27.2152, lng: 77.5030, tz: 5.5, nameHi: 'भरतपुर' },
  { id: 'bhilwara', name: 'Bhilwara', state: 'Rajasthan', country: 'India', lat: 25.3475, lng: 74.6408, tz: 5.5, nameHi: 'भीलवाड़ा' },
  { id: 'bikaner', name: 'Bikaner', state: 'Rajasthan', country: 'India', lat: 28.0229, lng: 73.3119, tz: 5.5, nameHi: 'बीकानेर' },
  { id: 'bundi', name: 'Bundi', state: 'Rajasthan', country: 'India', lat: 25.4415, lng: 75.6441, tz: 5.5, nameHi: 'बूंदी' },
  { id: 'chittaurgarh', name: 'Chittaurgarh', state: 'Rajasthan', country: 'India', lat: 24.8887, lng: 74.6269, tz: 5.5, nameHi: 'चित्तौड़गढ़' },
  { id: 'churu', name: 'Churu', state: 'Rajasthan', country: 'India', lat: 28.2900, lng: 74.9600, tz: 5.5, nameHi: 'चूरू (सालासर बालाजी)' },
  { id: 'dhaulpur', name: 'Dhaulpur', state: 'Rajasthan', country: 'India', lat: 26.7025, lng: 77.8934, tz: 5.5, nameHi: 'धौलपुर' },
  { id: 'dungarpur', name: 'Dungarpur', state: 'Rajasthan', country: 'India', lat: 23.8368, lng: 73.7149, tz: 5.5, nameHi: 'डूंगरपुर' },
  { id: 'ganganagar', name: 'Ganganagar', state: 'Rajasthan', country: 'India', lat: 29.9038, lng: 73.8772, tz: 5.5, nameHi: 'श्रीगंगानगर' },
  { id: 'hanumangarh', name: 'Hanumangarh', state: 'Rajasthan', country: 'India', lat: 29.5817, lng: 74.3294, tz: 5.5, nameHi: 'हनुमानगढ़' },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', country: 'India', lat: 26.9124, lng: 75.7873, tz: 5.5, nameHi: 'जयपुर (गोविंद देव जी)', isPopular: true },
  { id: 'jaisalmer', name: 'Jaisalmer', state: 'Rajasthan', country: 'India', lat: 26.9157, lng: 70.9083, tz: 5.5, nameHi: 'जैसलमेर' },
  { id: 'jalor', name: 'Jalor', state: 'Rajasthan', country: 'India', lat: 25.3444, lng: 72.6156, tz: 5.5, nameHi: 'जालौर' },
  { id: 'jhalawar', name: 'Jhalawar', state: 'Rajasthan', country: 'India', lat: 24.5973, lng: 76.1609, tz: 5.5, nameHi: 'झालावाड़' },
  { id: 'jhunjhunu', name: 'Jhunjhunu', state: 'Rajasthan', country: 'India', lat: 28.1289, lng: 75.3995, tz: 5.5, nameHi: 'झुंझुनू (राणी सती)' },
  { id: 'jodhpur', name: 'Jodhpur', state: 'Rajasthan', country: 'India', lat: 26.2389, lng: 73.0243, tz: 5.5, nameHi: 'जोधपुर', isPopular: true },
  { id: 'kishangarh', name: 'Kishangarh', state: 'Rajasthan', country: 'India', lat: 26.5772, lng: 74.8644, tz: 5.5, nameHi: 'किशनगढ़' },
  { id: 'kota', name: 'Kota', state: 'Rajasthan', country: 'India', lat: 25.2138, lng: 75.8648, tz: 5.5, nameHi: 'कोटा' },
  { id: 'merta', name: 'Merta', state: 'Rajasthan', country: 'India', lat: 26.6478, lng: 74.0322, tz: 5.5, nameHi: 'मेड़ता (मीराबाई)' },
  { id: 'nagaur', name: 'Nagaur', state: 'Rajasthan', country: 'India', lat: 27.2020, lng: 73.7439, tz: 5.5, nameHi: 'नागौर' },
  { id: 'nathdwara', name: 'Nathdwara', state: 'Rajasthan', country: 'India', lat: 24.9314, lng: 73.8186, tz: 5.5, nameHi: 'नाथद्वारा (श्रीनाथजी)', isPopular: true },
  { id: 'pali', name: 'Pali', state: 'Rajasthan', country: 'India', lat: 25.7711, lng: 73.3234, tz: 5.5, nameHi: 'पाली' },
  { id: 'phalodi', name: 'Phalodi', state: 'Rajasthan', country: 'India', lat: 27.1311, lng: 72.3639, tz: 5.5, nameHi: 'फलोदी' },
  { id: 'pushkar', name: 'Pushkar', state: 'Rajasthan', country: 'India', lat: 26.4897, lng: 74.5511, tz: 5.5, nameHi: 'पुष्कर (ब्रह्मा मन्दिर)', isPopular: true },
  { id: 'sawai-madhopur', name: 'Sawai Madhopur', state: 'Rajasthan', country: 'India', lat: 25.9928, lng: 76.3526, tz: 5.5, nameHi: 'सवाई माधोपुर' },
  { id: 'shahpura', name: 'Shahpura', state: 'Rajasthan', country: 'India', lat: 25.6333, lng: 74.9333, tz: 5.5, nameHi: 'शाहपुरा' },
  { id: 'sikar', name: 'Sikar', state: 'Rajasthan', country: 'India', lat: 27.6094, lng: 75.1398, tz: 5.5, nameHi: 'सीकर (खाटू श्याम जी)', isPopular: true },
  { id: 'sirohi', name: 'Sirohi', state: 'Rajasthan', country: 'India', lat: 24.8826, lng: 72.8624, tz: 5.5, nameHi: 'सिरोही' },
  { id: 'tonk', name: 'Tonk', state: 'Rajasthan', country: 'India', lat: 26.1624, lng: 75.7885, tz: 5.5, nameHi: 'टोंक' },
  { id: 'udaipur', name: 'Udaipur', state: 'Rajasthan', country: 'India', lat: 24.5854, lng: 73.7125, tz: 5.5, nameHi: 'उदयपुर (एकलिंग जी)', isPopular: true },

  // --- SIKKIM ---
  { id: 'gangtok', name: 'Gangtok', state: 'Sikkim', country: 'India', lat: 27.3389, lng: 88.6065, tz: 5.5, nameHi: 'गंगटोक' },
  { id: 'gyalshing', name: 'Gyalshing', state: 'Sikkim', country: 'India', lat: 27.2833, lng: 88.2500, tz: 5.5, nameHi: 'गेजिंग' },
  { id: 'lachung', name: 'Lachung', state: 'Sikkim', country: 'India', lat: 27.6891, lng: 88.7430, tz: 5.5, nameHi: 'लाचुंग' },
  { id: 'mangan', name: 'Mangan', state: 'Sikkim', country: 'India', lat: 27.5050, lng: 88.5339, tz: 5.5, nameHi: 'मंगन' },

  // --- TAMIL NADU ---
  { id: 'arcot', name: 'Arcot', state: 'Tamil Nadu', country: 'India', lat: 12.9056, lng: 79.3333, tz: 5.5, nameHi: 'आरकोट' },
  { id: 'chengalpattu', name: 'Chengalpattu', state: 'Tamil Nadu', country: 'India', lat: 12.6841, lng: 79.9836, tz: 5.5, nameHi: 'चेंगलपट्टू' },
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', country: 'India', lat: 13.0827, lng: 80.2707, tz: 5.5, nameHi: 'चेन्नई (कपालेश्वर)', isPopular: true },
  { id: 'chidambaram', name: 'Chidambaram', state: 'Tamil Nadu', country: 'India', lat: 11.3992, lng: 79.6936, tz: 5.5, nameHi: 'चिदम्बरम (नटराज)' },
  { id: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', country: 'India', lat: 11.0168, lng: 76.9558, tz: 5.5, nameHi: 'कोयम्बटूर (ईशा योग)', isPopular: true },
  { id: 'cuddalore', name: 'Cuddalore', state: 'Tamil Nadu', country: 'India', lat: 11.7480, lng: 79.7714, tz: 5.5, nameHi: 'कुड्डालोर' },
  { id: 'dharmapuri', name: 'Dharmapuri', state: 'Tamil Nadu', country: 'India', lat: 12.1211, lng: 78.1582, tz: 5.5, nameHi: 'धर्मपुरी' },
  { id: 'dindigul', name: 'Dindigul', state: 'Tamil Nadu', country: 'India', lat: 10.3673, lng: 77.9803, tz: 5.5, nameHi: 'डिंडीगुल' },
  { id: 'erode', name: 'Erode', state: 'Tamil Nadu', country: 'India', lat: 11.3410, lng: 77.7172, tz: 5.5, nameHi: 'इरोड' },
  { id: 'kanchipuram', name: 'Kanchipuram', state: 'Tamil Nadu', country: 'India', lat: 12.8342, lng: 79.7036, tz: 5.5, nameHi: 'कांचीपुरम (कामाक्षी अम्मन)', isPopular: true },
  { id: 'kanniyakumari', name: 'Kanniyakumari', state: 'Tamil Nadu', country: 'India', lat: 8.0883, lng: 77.5385, tz: 5.5, nameHi: 'कन्याकुमारी', isPopular: true },
  { id: 'kodaikanal', name: 'Kodaikanal', state: 'Tamil Nadu', country: 'India', lat: 10.2381, lng: 77.4892, tz: 5.5, nameHi: 'कोडाइकनाल' },
  { id: 'kumbakonam', name: 'Kumbakonam', state: 'Tamil Nadu', country: 'India', lat: 10.9602, lng: 79.3845, tz: 5.5, nameHi: 'कुंभकोणम (नवग्रह मन्दिर)' },
  { id: 'madurai', name: 'Madurai', state: 'Tamil Nadu', country: 'India', lat: 9.9252, lng: 78.1198, tz: 5.5, nameHi: 'मदुरै (मीनाक्षी अम्मन)', isPopular: true },
  { id: 'mamallapuram', name: 'Mamallapuram', state: 'Tamil Nadu', country: 'India', lat: 12.6269, lng: 80.1927, tz: 5.5, nameHi: 'महाबलीपुरम' },
  { id: 'nagappattinam', name: 'Nagappattinam', state: 'Tamil Nadu', country: 'India', lat: 10.7672, lng: 79.8449, tz: 5.5, nameHi: 'नागापट्टिनम' },
  { id: 'nagercoil', name: 'Nagercoil', state: 'Tamil Nadu', country: 'India', lat: 8.1833, lng: 77.4119, tz: 5.5, nameHi: 'नागरकोइल' },
  { id: 'palayamkottai', name: 'Palayamkottai', state: 'Tamil Nadu', country: 'India', lat: 8.7139, lng: 77.7347, tz: 5.5, nameHi: 'पलायमकोट्टई' },
  { id: 'pudukkottai', name: 'Pudukkottai', state: 'Tamil Nadu', country: 'India', lat: 10.3797, lng: 78.8208, tz: 5.5, nameHi: 'पुदुक्कोट्टई' },
  { id: 'rajapalayam', name: 'Rajapalayam', state: 'Tamil Nadu', country: 'India', lat: 9.4533, lng: 77.5547, tz: 5.5, nameHi: 'राजपालयम' },
  { id: 'ramanathapuram', name: 'Ramanathapuram', state: 'Tamil Nadu', country: 'India', lat: 9.3639, lng: 78.8395, tz: 5.5, nameHi: 'रामनाथपुरम (रामेश्वरम)', isPopular: true },
  { id: 'salem', name: 'Salem', state: 'Tamil Nadu', country: 'India', lat: 11.6643, lng: 78.1460, tz: 5.5, nameHi: 'सेलम' },
  { id: 'thanjavur', name: 'Thanjavur', state: 'Tamil Nadu', country: 'India', lat: 10.7870, lng: 79.1378, tz: 5.5, nameHi: 'तंजावुर (बृहदेश्वर)', isPopular: true },
  { id: 'tiruchchirappalli', name: 'Tiruchchirappalli', state: 'Tamil Nadu', country: 'India', lat: 10.7905, lng: 78.7047, tz: 5.5, nameHi: 'तिरुचिरापल्ली (श्रीरंगम)', isPopular: true },
  { id: 'tirunelveli', name: 'Tirunelveli', state: 'Tamil Nadu', country: 'India', lat: 8.7139, lng: 77.7567, tz: 5.5, nameHi: 'तिरुनेलवेली' },
  { id: 'tiruppur', name: 'Tiruppur', state: 'Tamil Nadu', country: 'India', lat: 11.1085, lng: 77.3411, tz: 5.5, nameHi: 'तिरुपूर' },
  { id: 'thoothukudi', name: 'Thoothukudi', state: 'Tamil Nadu', country: 'India', lat: 8.7642, lng: 78.1348, tz: 5.5, nameHi: 'थूथुकुडी (तूतीकोरिन)' },
  { id: 'udhagamandalam', name: 'Udhagamandalam', state: 'Tamil Nadu', country: 'India', lat: 11.4102, lng: 76.6950, tz: 5.5, nameHi: 'ऊटी (उधगमंडलम)' },
  { id: 'vellore', name: 'Vellore', state: 'Tamil Nadu', country: 'India', lat: 12.9165, lng: 79.1325, tz: 5.5, nameHi: 'वेल्लोर (स्वर्ण मन्दिर)' },

  // --- TELANGANA ---
  { id: 'hyderabad', name: 'Hyderabad', state: 'Telangana', country: 'India', lat: 17.3850, lng: 78.4867, tz: 5.5, nameHi: 'हैदराबाद (भाग्यनगर)', isPopular: true },
  { id: 'karimnagar', name: 'Karimnagar', state: 'Telangana', country: 'India', lat: 18.4386, lng: 79.1288, tz: 5.5, nameHi: 'करीमनगर' },
  { id: 'khammam', name: 'Khammam', state: 'Telangana', country: 'India', lat: 17.2473, lng: 80.1514, tz: 5.5, nameHi: 'खम्मम' },
  { id: 'mahbubnagar', name: 'Mahbubnagar', state: 'Telangana', country: 'India', lat: 16.7433, lng: 77.9982, tz: 5.5, nameHi: 'महबूबनगर' },
  { id: 'nizamabad', name: 'Nizamabad', state: 'Telangana', country: 'India', lat: 18.6725, lng: 78.0941, tz: 5.5, nameHi: 'निजामाबाद' },
  { id: 'sangareddi', name: 'Sangareddi', state: 'Telangana', country: 'India', lat: 17.6191, lng: 78.0811, tz: 5.5, nameHi: 'संगारेड्डी' },
  { id: 'warangal', name: 'Warangal', state: 'Telangana', country: 'India', lat: 17.9689, lng: 79.5941, tz: 5.5, nameHi: 'वारंगल (भद्रकाली)' },

  // --- TRIPURA ---
  { id: 'agartala', name: 'Agartala', state: 'Tripura', country: 'India', lat: 23.8315, lng: 91.2868, tz: 5.5, nameHi: 'अगरतला (त्रिपुर सुन्दरी)' },

  // --- UTTAR PRADESH ---
  { id: 'agra', name: 'Agra', state: 'Uttar Pradesh', country: 'India', lat: 27.1767, lng: 78.0081, tz: 5.5, nameHi: 'आगरा', isPopular: true },
  { id: 'aligarh', name: 'Aligarh', state: 'Uttar Pradesh', country: 'India', lat: 27.8974, lng: 78.0880, tz: 5.5, nameHi: 'अलीगढ़' },
  { id: 'amroha', name: 'Amroha', state: 'Uttar Pradesh', country: 'India', lat: 28.9044, lng: 78.4684, tz: 5.5, nameHi: 'अमरोहा' },
  { id: 'ayodhya', name: 'Ayodhya', state: 'Uttar Pradesh', country: 'India', lat: 26.7922, lng: 82.1998, tz: 5.5, nameHi: 'अयोध्या धाम (श्री राम जन्मभूमि)', isPopular: true },
  { id: 'azamgarh', name: 'Azamgarh', state: 'Uttar Pradesh', country: 'India', lat: 26.0738, lng: 83.1859, tz: 5.5, nameHi: 'आजमगढ़' },
  { id: 'bahraich', name: 'Bahraich', state: 'Uttar Pradesh', country: 'India', lat: 27.5705, lng: 81.5977, tz: 5.5, nameHi: 'बहराइच' },
  { id: 'ballia', name: 'Ballia', state: 'Uttar Pradesh', country: 'India', lat: 25.7584, lng: 84.1482, tz: 5.5, nameHi: 'बलिया (भृगु आश्रम)' },
  { id: 'banda', name: 'Banda', state: 'Uttar Pradesh', country: 'India', lat: 25.4754, lng: 80.3347, tz: 5.5, nameHi: 'बांदा' },
  { id: 'bara-banki', name: 'Bara Banki', state: 'Uttar Pradesh', country: 'India', lat: 26.9268, lng: 81.1834, tz: 5.5, nameHi: 'बाराबंकी' },
  { id: 'bareilly', name: 'Bareilly', state: 'Uttar Pradesh', country: 'India', lat: 28.3670, lng: 79.4304, tz: 5.5, nameHi: 'बरेली' },
  { id: 'basti', name: 'Basti', state: 'Uttar Pradesh', country: 'India', lat: 26.7999, lng: 82.7630, tz: 5.5, nameHi: 'बस्ती' },
  { id: 'bijnor', name: 'Bijnor', state: 'Uttar Pradesh', country: 'India', lat: 29.3724, lng: 78.1358, tz: 5.5, nameHi: 'बिजनौर' },
  { id: 'bithur', name: 'Bithur', state: 'Uttar Pradesh', country: 'India', lat: 26.6167, lng: 80.2667, tz: 5.5, nameHi: 'बिठूर (ब्रह्मावर्त)' },
  { id: 'budaun', name: 'Budaun', state: 'Uttar Pradesh', country: 'India', lat: 28.0384, lng: 79.1264, tz: 5.5, nameHi: 'बदायूँ' },
  { id: 'bulandshahr', name: 'Bulandshahr', state: 'Uttar Pradesh', country: 'India', lat: 28.4069, lng: 77.8498, tz: 5.5, nameHi: 'बुलंदशहर' },
  { id: 'deoria', name: 'Deoria', state: 'Uttar Pradesh', country: 'India', lat: 26.5024, lng: 83.7791, tz: 5.5, nameHi: 'देवरिया' },
  { id: 'etah', name: 'Etah', state: 'Uttar Pradesh', country: 'India', lat: 27.5583, lng: 78.6653, tz: 5.5, nameHi: 'एटा' },
  { id: 'etawah', name: 'Etawah', state: 'Uttar Pradesh', country: 'India', lat: 26.7769, lng: 79.0232, tz: 5.5, nameHi: 'इटावा' },
  { id: 'faizabad', name: 'Faizabad', state: 'Uttar Pradesh', country: 'India', lat: 26.7730, lng: 82.1458, tz: 5.5, nameHi: 'फैजाबाद' },
  { id: 'farrukhabad', name: 'Farrukhabad-cum-Fatehgarh', state: 'Uttar Pradesh', country: 'India', lat: 27.3833, lng: 79.5833, tz: 5.5, nameHi: 'फर्रुखाबाद' },
  { id: 'fatehpur', name: 'Fatehpur', state: 'Uttar Pradesh', country: 'India', lat: 25.9286, lng: 80.8130, tz: 5.5, nameHi: 'फतेहपुर' },
  { id: 'fatehpur-sikri', name: 'Fatehpur Sikri', state: 'Uttar Pradesh', country: 'India', lat: 27.0945, lng: 77.6679, tz: 5.5, nameHi: 'फतेहपुर सीकरी' },
  { id: 'ghaziabad', name: 'Ghaziabad', state: 'Uttar Pradesh', country: 'India', lat: 28.6692, lng: 77.4538, tz: 5.5, nameHi: 'गाजियाबाद' },
  { id: 'ghazipur', name: 'Ghazipur', state: 'Uttar Pradesh', country: 'India', lat: 25.5840, lng: 83.5770, tz: 5.5, nameHi: 'गाजीपुर' },
  { id: 'gonda', name: 'Gonda', state: 'Uttar Pradesh', country: 'India', lat: 27.1337, lng: 81.9619, tz: 5.5, nameHi: 'गोंडा' },
  { id: 'gorakhpur', name: 'Gorakhpur', state: 'Uttar Pradesh', country: 'India', lat: 26.7606, lng: 83.3732, tz: 5.5, nameHi: 'गोरखपुर (गोरखनाथ)', isPopular: true },
  { id: 'hamirpur-up', name: 'Hamirpur', state: 'Uttar Pradesh', country: 'India', lat: 25.9556, lng: 80.1517, tz: 5.5, nameHi: 'हमीरपुर (उ.प्र.)' },
  { id: 'hardoi', name: 'Hardoi', state: 'Uttar Pradesh', country: 'India', lat: 27.3949, lng: 80.1287, tz: 5.5, nameHi: 'हरदोई' },
  { id: 'hathras', name: 'Hathras', state: 'Uttar Pradesh', country: 'India', lat: 27.5968, lng: 78.0519, tz: 5.5, nameHi: 'हाथरस' },
  { id: 'jalaun', name: 'Jalaun', state: 'Uttar Pradesh', country: 'India', lat: 26.1457, lng: 79.3524, tz: 5.5, nameHi: 'जालौन' },
  { id: 'jaunpur', name: 'Jaunpur', state: 'Uttar Pradesh', country: 'India', lat: 25.7464, lng: 82.6837, tz: 5.5, nameHi: 'जौनपुर (यमदग्नि)' },
  { id: 'jhansi', name: 'Jhansi', state: 'Uttar Pradesh', country: 'India', lat: 25.4484, lng: 78.5685, tz: 5.5, nameHi: 'झाँसी' },
  { id: 'kannauj', name: 'Kannauj', state: 'Uttar Pradesh', country: 'India', lat: 27.0544, lng: 79.9149, tz: 5.5, nameHi: 'कन्नौज' },
  { id: 'kanpur', name: 'Kanpur', state: 'Uttar Pradesh', country: 'India', lat: 26.4499, lng: 80.3319, tz: 5.5, nameHi: 'कानपुर', isPopular: true },
  { id: 'lakhimpur', name: 'Lakhimpur', state: 'Uttar Pradesh', country: 'India', lat: 27.9463, lng: 80.7787, tz: 5.5, nameHi: 'लखीमपुर खीरी' },
  { id: 'lalitpur', name: 'Lalitpur', state: 'Uttar Pradesh', country: 'India', lat: 24.6897, lng: 78.4111, tz: 5.5, nameHi: 'ललितपुर' },
  { id: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', country: 'India', lat: 26.8467, lng: 80.9462, tz: 5.5, nameHi: 'लखनऊ (लक्ष्मणपुरी)', isPopular: true },
  { id: 'mainpuri', name: 'Mainpuri', state: 'Uttar Pradesh', country: 'India', lat: 27.2285, lng: 79.0289, tz: 5.5, nameHi: 'मैनपुरी' },
  { id: 'mathura', name: 'Mathura', state: 'Uttar Pradesh', country: 'India', lat: 27.4924, lng: 77.6737, tz: 5.5, nameHi: 'मथुरा (श्री कृष्ण जन्मभूमि)', isPopular: true },
  { id: 'meerut', name: 'Meerut', state: 'Uttar Pradesh', country: 'India', lat: 28.9845, lng: 77.7064, tz: 5.5, nameHi: 'मेरठ' },
  { id: 'mirzapur', name: 'Mirzapur-Vindhyachal', state: 'Uttar Pradesh', country: 'India', lat: 25.1337, lng: 82.5644, tz: 5.5, nameHi: 'मिर्जापुर (विन्ध्याचल शक्तिपीठ)', isPopular: true },
  { id: 'moradabad', name: 'Moradabad', state: 'Uttar Pradesh', country: 'India', lat: 28.8386, lng: 78.7733, tz: 5.5, nameHi: 'मुरादाबाद' },
  { id: 'muzaffarnagar', name: 'Muzaffarnagar', state: 'Uttar Pradesh', country: 'India', lat: 29.4727, lng: 77.7085, tz: 5.5, nameHi: 'मुजफ्फरनगर' },
  { id: 'partapgarh', name: 'Partapgarh', state: 'Uttar Pradesh', country: 'India', lat: 25.8967, lng: 81.9472, tz: 5.5, nameHi: 'प्रतापगढ़' },
  { id: 'pilibhit', name: 'Pilibhit', state: 'Uttar Pradesh', country: 'India', lat: 28.6277, lng: 79.8055, tz: 5.5, nameHi: 'पीलीभीत' },
  { id: 'prayagraj', name: 'Prayagraj', state: 'Uttar Pradesh', country: 'India', lat: 25.4358, lng: 81.8463, tz: 5.5, nameHi: 'प्रयागराज (तीर्थराज त्रिवेणी)', isPopular: true },
  { id: 'rae-bareli', name: 'Rae Bareli', state: 'Uttar Pradesh', country: 'India', lat: 26.2303, lng: 81.2409, tz: 5.5, nameHi: 'रायबरेली' },
  { id: 'rampur', name: 'Rampur', state: 'Uttar Pradesh', country: 'India', lat: 28.8038, lng: 79.0261, tz: 5.5, nameHi: 'रामपुर' },
  { id: 'saharanpur', name: 'Saharanpur', state: 'Uttar Pradesh', country: 'India', lat: 29.9640, lng: 77.5460, tz: 5.5, nameHi: 'सहारनपुर (शाकम्भरी देवी)' },
  { id: 'sambhal', name: 'Sambhal', state: 'Uttar Pradesh', country: 'India', lat: 28.5836, lng: 78.5547, tz: 5.5, nameHi: 'सम्भल (कल्कि तीर्थ)' },
  { id: 'shahjahanpur', name: 'Shahjahanpur', state: 'Uttar Pradesh', country: 'India', lat: 27.8805, lng: 79.9114, tz: 5.5, nameHi: 'शाहजहांपुर' },
  { id: 'sitapur', name: 'Sitapur', state: 'Uttar Pradesh', country: 'India', lat: 27.5685, lng: 80.6806, tz: 5.5, nameHi: 'सीतापुर (नैमिषारण्य)', isPopular: true },
  { id: 'sultanpur', name: 'Sultanpur', state: 'Uttar Pradesh', country: 'India', lat: 26.2648, lng: 82.0727, tz: 5.5, nameHi: 'सुलतानपुर' },
  { id: 'varanasi', name: 'Varanasi', state: 'Uttar Pradesh', country: 'India', lat: 25.3176, lng: 82.9739, tz: 5.5, nameHi: 'काशी (वाराणसी धाम)', isPopular: true },

  // --- UTTARAKHAND ---
  { id: 'almora', name: 'Almora', state: 'Uttarakhand', country: 'India', lat: 29.5971, lng: 79.6591, tz: 5.5, nameHi: 'अल्मोड़ा (जागेश्वर)' },
  { id: 'dehra-dun', name: 'Dehra Dun', state: 'Uttarakhand', country: 'India', lat: 30.3165, lng: 78.0322, tz: 5.5, nameHi: 'देहरादून', isPopular: true },
  { id: 'haridwar', name: 'Haridwar', state: 'Uttarakhand', country: 'India', lat: 29.9457, lng: 78.1642, tz: 5.5, nameHi: 'हरिद्वार (हर की पौड़ी)', isPopular: true },
  { id: 'mussoorie', name: 'Mussoorie', state: 'Uttarakhand', country: 'India', lat: 30.4598, lng: 78.0644, tz: 5.5, nameHi: 'मसूरी' },
  { id: 'nainital', name: 'Nainital', state: 'Uttarakhand', country: 'India', lat: 29.3803, lng: 79.4636, tz: 5.5, nameHi: 'नैनीताल' },
  { id: 'pithoragarh', name: 'Pithoragarh', state: 'Uttarakhand', country: 'India', lat: 29.5829, lng: 80.2182, tz: 5.5, nameHi: 'पिथौरागढ़' },
  { id: 'tehri', name: 'Tehri', state: 'Uttarakhand', country: 'India', lat: 30.3904, lng: 78.4802, tz: 5.5, nameHi: 'टिहरी गढ़वाल' },
  { id: 'kedarnath', name: 'Kedarnath', state: 'Uttarakhand', country: 'India', lat: 30.7352, lng: 79.0669, tz: 5.5, nameHi: 'श्री केदारनाथ ज्योतिर्लिंग', isPopular: true },
  { id: 'badrinath', name: 'Badrinath', state: 'Uttarakhand', country: 'India', lat: 30.7433, lng: 79.4938, tz: 5.5, nameHi: 'श्री बद्रीनाथ धाम', isPopular: true },
  { id: 'rishikesh', name: 'Rishikesh', state: 'Uttarakhand', country: 'India', lat: 30.0869, lng: 78.2676, tz: 5.5, nameHi: 'ऋषिकेश', isPopular: true },

  // --- WEST BENGAL ---
  { id: 'alipore', name: 'Alipore', state: 'West Bengal', country: 'India', lat: 22.5333, lng: 88.3333, tz: 5.5, nameHi: 'अलीपुर' },
  { id: 'alipur-duar', name: 'Alipur Duar', state: 'West Bengal', country: 'India', lat: 26.4919, lng: 89.5271, tz: 5.5, nameHi: 'अलीपुरद्वार' },
  { id: 'asansol', name: 'Asansol', state: 'West Bengal', country: 'India', lat: 23.6739, lng: 86.9524, tz: 5.5, nameHi: 'आसनसोल', isPopular: true },
  { id: 'baharampur', name: 'Baharampur', state: 'West Bengal', country: 'India', lat: 24.0988, lng: 88.2679, tz: 5.5, nameHi: 'बहरमपुर' },
  { id: 'bally', name: 'Bally', state: 'West Bengal', country: 'India', lat: 22.6500, lng: 88.3400, tz: 5.5, nameHi: 'बाली' },
  { id: 'balurghat', name: 'Balurghat', state: 'West Bengal', country: 'India', lat: 25.2173, lng: 88.7667, tz: 5.5, nameHi: 'बालुरघाट' },
  { id: 'bankura', name: 'Bankura', state: 'West Bengal', country: 'India', lat: 23.2323, lng: 87.0716, tz: 5.5, nameHi: 'बांकुड़ा' },
  { id: 'baranagar', name: 'Baranagar', state: 'West Bengal', country: 'India', lat: 22.6415, lng: 88.3718, tz: 5.5, nameHi: 'बरानगर' },
  { id: 'barasat', name: 'Barasat', state: 'West Bengal', country: 'India', lat: 22.7237, lng: 88.4812, tz: 5.5, nameHi: 'बारासात' },
  { id: 'barrackpore', name: 'Barrackpore', state: 'West Bengal', country: 'India', lat: 22.7662, lng: 88.3686, tz: 5.5, nameHi: 'बैरकपुर' },
  { id: 'basirhat', name: 'Basirhat', state: 'West Bengal', country: 'India', lat: 22.6616, lng: 88.8687, tz: 5.5, nameHi: 'बसीरहाट' },
  { id: 'bhatpara', name: 'Bhatpara', state: 'West Bengal', country: 'India', lat: 22.8681, lng: 88.4069, tz: 5.5, nameHi: 'भाटपाड़ा' },
  { id: 'bishnupur', name: 'Bishnupur', state: 'West Bengal', country: 'India', lat: 22.9860, lng: 87.3190, tz: 5.5, nameHi: 'विष्णुपुर (टेराकोटा मन्दिर)' },
  { id: 'budge-budge', name: 'Budge Budge', state: 'West Bengal', country: 'India', lat: 22.4824, lng: 88.1818, tz: 5.5, nameHi: 'बजबज' },
  { id: 'burdwan', name: 'Burdwan', state: 'West Bengal', country: 'India', lat: 23.2324, lng: 87.8615, tz: 5.5, nameHi: 'बर्दवान' },
  { id: 'chandernagore', name: 'Chandernagore', state: 'West Bengal', country: 'India', lat: 22.8671, lng: 88.3674, tz: 5.5, nameHi: 'चंदननगर' },
  { id: 'darjeeling', name: 'Darjeeling', state: 'West Bengal', country: 'India', lat: 27.0410, lng: 88.2663, tz: 5.5, nameHi: 'दार्जिलिंग' },
  { id: 'diamond-harbour', name: 'Diamond Harbour', state: 'West Bengal', country: 'India', lat: 22.1919, lng: 88.1906, tz: 5.5, nameHi: 'डायमंड हार्बर' },
  { id: 'dum-dum', name: 'Dum Dum', state: 'West Bengal', country: 'India', lat: 22.6420, lng: 88.4312, tz: 5.5, nameHi: 'दमदम' },
  { id: 'durgapur', name: 'Durgapur', state: 'West Bengal', country: 'India', lat: 23.5204, lng: 87.3119, tz: 5.5, nameHi: 'दुर्गापुर' },
  { id: 'halisahar', name: 'Halisahar', state: 'West Bengal', country: 'India', lat: 22.9463, lng: 88.4172, tz: 5.5, nameHi: 'हालिशहर' },
  { id: 'haora', name: 'Haora', state: 'West Bengal', country: 'India', lat: 22.5958, lng: 88.2636, tz: 5.5, nameHi: 'हावड़ा' },
  { id: 'hugli', name: 'Hugli', state: 'West Bengal', country: 'India', lat: 22.9014, lng: 88.3968, tz: 5.5, nameHi: 'हुगली' },
  { id: 'ingraj-bazar', name: 'Ingraj Bazar', state: 'West Bengal', country: 'India', lat: 25.0039, lng: 88.1462, tz: 5.5, nameHi: 'इंग्लिश बाजार (मालदा)' },
  { id: 'jalpaiguri', name: 'Jalpaiguri', state: 'West Bengal', country: 'India', lat: 26.5405, lng: 88.7196, tz: 5.5, nameHi: 'जलपाईगुड़ी' },
  { id: 'kalimpong', name: 'Kalimpong', state: 'West Bengal', country: 'India', lat: 27.0667, lng: 88.4667, tz: 5.5, nameHi: 'कालिम्पोंग' },
  { id: 'kamarhati', name: 'Kamarhati', state: 'West Bengal', country: 'India', lat: 22.6714, lng: 88.3739, tz: 5.5, nameHi: 'कमरहटी' },
  { id: 'kanchrapara', name: 'Kanchrapara', state: 'West Bengal', country: 'India', lat: 22.9372, lng: 88.4339, tz: 5.5, nameHi: 'कांचरापाड़ा' },
  { id: 'kharagpur', name: 'Kharagpur', state: 'West Bengal', country: 'India', lat: 22.3460, lng: 87.2320, tz: 5.5, nameHi: 'खड़गपुर' },
  { id: 'cooch-behar', name: 'Cooch Behar', state: 'West Bengal', country: 'India', lat: 26.3452, lng: 89.4482, tz: 5.5, nameHi: 'कूचबिहार' },
  { id: 'kolkata', name: 'Kolkata', state: 'West Bengal', country: 'India', lat: 22.5726, lng: 88.3639, tz: 5.5, nameHi: 'कोलकाता (कालीघाट)', isPopular: true },
  { id: 'krishnanagar', name: 'Krishnanagar', state: 'West Bengal', country: 'India', lat: 23.4042, lng: 88.5022, tz: 5.5, nameHi: 'कृष्णनगर' },
  { id: 'malda', name: 'Malda', state: 'West Bengal', country: 'India', lat: 25.0039, lng: 88.1462, tz: 5.5, nameHi: 'मालदा' },
  { id: 'midnapore', name: 'Midnapore', state: 'West Bengal', country: 'India', lat: 22.4257, lng: 87.3199, tz: 5.5, nameHi: 'मेदिनीपुर' },
  { id: 'murshidabad', name: 'Murshidabad', state: 'West Bengal', country: 'India', lat: 24.1814, lng: 88.2709, tz: 5.5, nameHi: 'मुर्शिदाबाद' },
  { id: 'nabadwip', name: 'Nabadwip', state: 'West Bengal', country: 'India', lat: 23.4080, lng: 88.3657, tz: 5.5, nameHi: 'नवद्वीप (मायापुर)', isPopular: true },
  { id: 'palashi', name: 'Palashi', state: 'West Bengal', country: 'India', lat: 23.7894, lng: 88.2572, tz: 5.5, nameHi: 'पलाशी (प्लासी)' },
  { id: 'panihati', name: 'Panihati', state: 'West Bengal', country: 'India', lat: 22.6936, lng: 88.3739, tz: 5.5, nameHi: 'पानीहाटी' },
  { id: 'purulia', name: 'Purulia', state: 'West Bengal', country: 'India', lat: 23.3322, lng: 86.3652, tz: 5.5, nameHi: 'पुरुलिया' },
  { id: 'raiganj', name: 'Raiganj', state: 'West Bengal', country: 'India', lat: 25.6190, lng: 88.1256, tz: 5.5, nameHi: 'रायगंज' },
  { id: 'santipur', name: 'Santipur', state: 'West Bengal', country: 'India', lat: 23.2506, lng: 88.4339, tz: 5.5, nameHi: 'शांतिपुर' },
  { id: 'shantiniketan', name: 'Shantiniketan', state: 'West Bengal', country: 'India', lat: 23.6797, lng: 87.6897, tz: 5.5, nameHi: 'शांतिनिकेतन' },
  { id: 'shrirampur', name: 'Shrirampur', state: 'West Bengal', country: 'India', lat: 22.7523, lng: 88.3410, tz: 5.5, nameHi: 'श्रीरामपुर' },
  { id: 'siliguri', name: 'Siliguri', state: 'West Bengal', country: 'India', lat: 26.7271, lng: 88.3953, tz: 5.5, nameHi: 'सिलीगुड़ी' },
  { id: 'siuri', name: 'Siuri', state: 'West Bengal', country: 'India', lat: 23.9056, lng: 87.5256, tz: 5.5, nameHi: 'सिउड़ी' },
  { id: 'tamluk', name: 'Tamluk', state: 'West Bengal', country: 'India', lat: 22.2982, lng: 87.9228, tz: 5.5, nameHi: 'तामलुक (वर्गभीमा)' },
  { id: 'titagarh', name: 'Titagarh', state: 'West Bengal', country: 'India', lat: 22.7381, lng: 88.3742, tz: 5.5, nameHi: 'टीटागढ़' },

  // --- MAJOR INTERNATIONAL DIASPORA HUBS ---
  { id: 'dubai', name: 'Dubai', state: 'Dubai', country: 'UAE', lat: 25.2048, lng: 55.2708, tz: 4.0, nameHi: 'दुबई (यूएई)' },
  { id: 'london', name: 'London', state: 'England', country: 'UK', lat: 51.5074, lng: -0.1278, tz: 1.0, nameHi: 'लंदन (यूके)' },
  { id: 'new-york', name: 'New York', state: 'NY', country: 'USA', lat: 40.7128, lng: -74.0060, tz: -4.0, nameHi: 'न्यूयॉर्क (यूएसए)' },
  { id: 'san-francisco', name: 'San Francisco', state: 'CA', country: 'USA', lat: 37.7749, lng: -122.4194, tz: -7.0, nameHi: 'सैन फ्रांसिस्को (यूएसए)' },
  { id: 'singapore', name: 'Singapore', state: 'Singapore', country: 'Singapore', lat: 1.3521, lng: 103.8198, tz: 8.0, nameHi: 'सिंगापुर' },
  { id: 'toronto', name: 'Toronto', state: 'Ontario', country: 'Canada', lat: 43.6532, lng: -79.3832, tz: -4.0, nameHi: 'टोरंटो (कनाडा)' },
  { id: 'sydney', name: 'Sydney', state: 'NSW', country: 'Australia', lat: -33.8688, lng: 151.2093, tz: 10.0, nameHi: 'सिडनी (ऑस्ट्रेलिया)' }
];

export const DEFAULT_CITY = CITIES.find(c => c.id === 'dhanbad') || CITIES[0];

// Group cities by State / Territory
export const CITIES_BY_STATE = CITIES.reduce((acc, city) => {
  const stateKey = city.state;
  if (!acc[stateKey]) {
    acc[stateKey] = [];
  }
  acc[stateKey].push(city);
  return acc;
}, {});

export function searchCities(query) {
  if (!query || !query.trim()) return CITIES.slice(0, 30);
  const q = query.toLowerCase().trim();
  const tokens = q.split(/[\s,]+/).filter((t) => t.length > 0);
  return CITIES.filter((c) => {
    const nameLower = c.name.toLowerCase();
    const stateLower = c.state.toLowerCase();
    const nameHi = c.nameHi || '';
    const countryLower = c.country.toLowerCase();
    if (
      nameLower.includes(q) ||
      stateLower.includes(q) ||
      nameHi.includes(q) ||
      countryLower.includes(q)
    ) {
      return true;
    }
    return tokens.every(
      (tok) =>
        nameLower.includes(tok) ||
        stateLower.includes(tok) ||
        nameHi.includes(tok) ||
        countryLower.includes(tok)
    );
  });
}

export function findCityById(id) {
  return CITIES.find(c => c.id === id) || DEFAULT_CITY;
}