/**
 * CosmicTantra V34 — Report Generator
 * Generates formatted text summaries for Kundali analysis
 */

export function generateShareableReport(kundali, panchang, currentDasha, name = 'Seeker') {
  if (!kundali) return 'Please calculate Kundali first.';

  const lines = [
    `🕉️ COSMICTANTRA — Vedic Jyotish Kundali Report`,
    `═════════════════════════════════════════════`,
    ``,
    `👤 Name: ${name}`,
    `📅 Birth: ${kundali.metadata?.birthDate?.slice(0, 10)}`,
    `📍 Location: ${kundali.metadata?.latitude?.toFixed(2)}°N, ${kundali.metadata?.longitude?.toFixed(2)}°E`,
    ``,
    `🌟 LAGNA: ${kundali.lagna?.rasiName} (${kundali.lagna?.nakshatra?.name} Nakshatra)`,
    ``,
    `🪐 PLANETARY POSITIONS`,
    `─────────────────────`,
    ...Object.entries(kundali.planets || {}).map(([name, p]) =>
      `${name.padEnd(9)} → ${p.rasiName.padEnd(13)} House ${p.house}  ${p.nakshatra?.name.padEnd(18)} [${p.status}]`
    ),
    ``,
    `⏳ CURRENT DASHA: ${currentDasha?.planet || '—'} (${currentDasha?.percentDone || 0}% complete)`,
    ``,
  ];

  if (panchang) {
    lines.push(
      `📅 TODAY'S PANCHANG (${panchang.date})`,
      `─────────────────────────────────`,
      `Tithi:     ${panchang.tithi?.name} — ${panchang.tithi?.meaning}`,
      `Nakshatra: ${panchang.nakshatra?.name} (Pada ${panchang.nakshatra?.pada})`,
      `Yoga:      ${panchang.yoga?.name}`,
      `Vara:      ${panchang.vara?.day} (${panchang.vara?.planet})`,
      `Rahu Kala: ${panchang.rahuKala?.start} – ${panchang.rahuKala?.end}`,
    );
  }

  lines.push(
    ``,
    `═════════════════════════════════════════════`,
    `Generated by CosmicTantra V34 · ${new Date().toLocaleDateString('en-IN')}`,
  );

  return lines.join('\n');
}

export default { generateShareableReport };
