'use client';

/**
 * EvidenceBackedPattern — PRESENTATIONAL ONLY (Sprint B.1 §3/§4).
 *
 * CT_UX_INV_002: a presentation component may not manufacture astrological
 * facts. This file must never contain a hardcoded planet, house, degree,
 * yoga, dasha, shadbala, ashtakavarga, or classical conclusion. Everything
 * it renders arrives as props — generated by the READ-ONLY adapter
 * (`src/lib/presentation/kundliOverviewAdapter.ts`) from engine structures.
 *
 * It deliberately does NOT render percentile scores and is NOT connected to
 * the legacy 0–100 Executive Life Gauge. `representation` is a qualitative
 * enum; `validationStatus` and `scholarJudgementRequired` come from the
 * engine/adapter and are displayed as status, never as a score.
 */

import React from 'react';
import { ChevronRight, ShieldCheck, Compass, AlertTriangle, Eye, Scale } from 'lucide-react';
import { TRANSLATIONS } from '@/lib/translations';
import type {
  EvidenceNodePresentation,
  PatternRepresentation,
  PatternValidationStatus,
} from '@/lib/presentation/kundliOverviewAdapter';

type Dict = Record<string, string>;

export interface EvidenceBackedPatternProps {
  id: string;
  category: 'CAREER' | 'DASHA' | 'STRUCTURE';
  /** i18n key into `pattern` section. */
  titleKey: string;
  titleHiKey: string;
  representation: PatternRepresentation;
  summary: string[];
  evidence: EvidenceNodePresentation[];
  validationStatus: PatternValidationStatus;
  scholarJudgementRequired: boolean;
  sourceStatus?: string;
  lang?: string;
  onViewEvidence?: (evidenceId: string) => void;
  onAskScholar?: () => void;
  /** Optional extra action rendered as buttons (consumer-supplied handlers). */
  actions?: Array<{ id: string; label: string; onTrigger: () => void }>;
}

const REPRESENTATION_ICON: Record<PatternRepresentation, React.ComponentType<{ className?: string }>> = {
  STRONGLY_REPRESENTED: ShieldCheck,
  REPRESENTED: Compass,
  MIXED: Scale,
  WEAKLY_REPRESENTED: AlertTriangle,
  UNRESOLVED: AlertTriangle,
};

const REPRESENTATION_TONE: Record<PatternRepresentation, string> = {
  STRONGLY_REPRESENTED: 'text-emerald-600 dark:text-emerald-400',
  REPRESENTED: 'text-amber-600 dark:text-amber-400',
  MIXED: 'text-sky-600 dark:text-sky-400',
  WEAKLY_REPRESENTED: 'text-slate-600 dark:text-slate-400',
  UNRESOLVED: 'text-stone-500 dark:text-stone-400',
};

const VALIDATION_TONE: Record<PatternValidationStatus, string> = {
  VALIDATED: 'text-emerald-600 dark:text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
  VALIDATION_PENDING: 'text-amber-600 dark:text-amber-400 border-amber-500/30 bg-amber-500/10',
  SCHOLAR_JUDGEMENT_REQUIRED: 'text-sky-600 dark:text-sky-400 border-sky-500/30 bg-sky-500/10',
  UNAVAILABLE: 'text-slate-500 dark:text-slate-400 border-slate-500/30 bg-slate-500/10',
};

export default function EvidenceBackedPattern({
  id,
  titleKey,
  titleHiKey,
  representation,
  summary,
  evidence,
  validationStatus,
  scholarJudgementRequired,
  sourceStatus,
  lang = 'en',
  onViewEvidence,
  onAskScholar,
  actions,
}: EvidenceBackedPatternProps) {
  const t: Dict = (TRANSLATIONS[lang] as any)?.pattern || (TRANSLATIONS.en as any).pattern;
  const title = lang === 'hi' ? t[titleHiKey] ?? t[titleKey] : t[titleKey] ?? titleKey;
  const RepresentationIcon = REPRESENTATION_ICON[representation] ?? Compass;

  const representationLabel = (
    {
      STRONGLY_REPRESENTED: 'stronglyRepresented',
      REPRESENTED: 'represented',
      MIXED: 'mixed',
      WEAKLY_REPRESENTED: 'weaklyRepresented',
      UNRESOLVED: 'unresolved',
    } as Record<PatternRepresentation, string>
  )[representation];

  const validationLabel = (
    {
      VALIDATED: 'validated',
      VALIDATION_PENDING: 'validationPending',
      SCHOLAR_JUDGEMENT_REQUIRED: 'scholarJudgementRequired',
      UNAVAILABLE: 'unavailable',
    } as Record<PatternValidationStatus, string>
  )[validationStatus];

  return (
    <section
      data-testid="evidence-backed-pattern"
      data-pattern-id={id}
      data-representation={representation}
      data-validation-status={validationStatus}
      className="rounded-2xl border border-[#8E6F1D]/20 dark:border-[#D4AF37]/25 bg-white/70 dark:bg-[#0E101D]/70 p-5 space-y-4"
    >
      <header className="flex items-start justify-between gap-3">
        <div>
          <h3 className="font-editorial text-lg font-bold">{title}</h3>
          <div className={`mt-1 inline-flex items-center gap-1.5 text-xs font-mono-data font-bold ${REPRESENTATION_TONE[representation]}`}>
            <RepresentationIcon className="w-3.5 h-3.5" aria-hidden="true" />
            <span>{t[representationLabel] ?? representationLabel}</span>
          </div>
        </div>
        <span
          data-testid="evidence-backed-pattern-validation"
          className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full border text-[10px] font-mono-data font-bold ${VALIDATION_TONE[validationStatus]}`}
        >
          {t[validationLabel] ?? validationLabel}
        </span>
      </header>

      {summary && summary.length > 0 && (
        <div className="space-y-1.5">
          {summary.map((line, i) => (
            <p key={i} data-testid="evidence-backed-pattern-summary" className="text-sm leading-relaxed opacity-90">
              {line}
            </p>
          ))}
        </div>
      )}

      {scholarJudgementRequired && (
        <p data-testid="evidence-backed-pattern-scholar" className="text-xs font-mono-data text-sky-600 dark:text-sky-400">
          ◇ {t.scholarJudgementRequired}
        </p>
      )}

      {evidence.length > 0 && (
        <ul data-testid="evidence-backed-pattern-evidence" className="space-y-2">
          {evidence.map((node) => (
            <li
              key={node.id}
              data-testid={`evidence-backed-pattern-evidence-${node.id}`}
              data-content-type={node.contentType}
              data-polarity={node.polarity}
              className="flex items-start gap-3 rounded-xl border border-black/5 dark:border-white/10 p-3"
            >
              <Eye className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" aria-hidden="true" />
              <div className="min-w-0 flex-1">
                <p className="text-sm">{node.statement}</p>
                {node.notCalculatedReason && (
                  <p className="text-[11px] mt-1 opacity-60">{node.notCalculatedReason}</p>
                )}
                <div className="mt-1 flex flex-wrap gap-1.5">
                  <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-black/5 dark:bg-white/10 font-mono-data font-bold tracking-wide">
                    {node.contentType.replace(/_/g, ' ')}
                  </span>
                  {onViewEvidence && (
                    <button
                      type="button"
                      onClick={() => onViewEvidence(node.id)}
                      className="text-[10px] font-mono-data font-bold text-[#8E6F1D] dark:text-[#F0C968] hover:underline cursor-pointer"
                    >
                      {t.viewEvidence} →
                    </button>
                  )}
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}

      <footer className="flex flex-wrap items-center gap-2 pt-1">
        {sourceStatus && <span className="text-[10px] font-mono-data opacity-50">{sourceStatus}</span>}
        {onAskScholar && (
          <button
            type="button"
            onClick={onAskScholar}
            className="inline-flex items-center gap-1.5 min-h-11 px-4 rounded-xl bg-[#8E6F1D] hover:bg-[#A88424] text-white text-xs font-mono-data font-bold transition-colors cursor-pointer"
          >
            {t.askScholar} <ChevronRight className="w-3.5 h-3.5" aria-hidden="true" />
          </button>
        )}
        {actions?.map((action) => (
          <button
            key={action.id}
            type="button"
            onClick={action.onTrigger}
            data-testid={`evidence-backed-pattern-action-${action.id}`}
            className="inline-flex items-center gap-1.5 min-h-11 px-4 rounded-xl border border-[#8E6F1D]/30 dark:border-[#D4AF37]/30 text-xs font-mono-data font-bold cursor-pointer hover:bg-black/5 dark:hover:bg-white/10 transition-colors"
          >
            {action.label}
          </button>
        ))}
      </footer>
    </section>
  );
}
