import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { buildCoverageReport, stableCoverageSummary } from '../src/lib/granth/coverage';
import { loadBook, __clearBookCache } from '../src/lib/granth/registry';

/**
 * Reproducible per-edition coverage.
 *
 * Deterministic (no network, no clock-dependent assertions). It also writes
 * the human-readable artefacts under docs/granth/, so running this spec is
 * the way to regenerate them.
 */
const OUT_DIR = path.resolve(__dirname, '../docs/granth');
const JSON_PATH = path.join(OUT_DIR, 'coverage.json');
const MD_PATH = path.join(OUT_DIR, 'COVERAGE-REPORT.md');

function toMarkdown(report: Awaited<ReturnType<typeof buildCoverageReport>>): string {
  const lines: string[] = [];
  lines.push('# Granth coverage report');
  lines.push('');
  lines.push(`Generated by \`${report.generator}\` (deterministic; regenerate with \`npx playwright test tests/granth-coverage.spec.ts\`).`);
  lines.push('');
  lines.push(
    'Coverage compares the stored corpus against a per-edition manifest. It is **not** an independent collation against a printed edition unless the manifest says so.',
  );
  lines.push('');
  lines.push('| Book | Edition | Status | Stored rows | Verses stored | Expected verses | Missing | Extra | Corrupt |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const book of report.books) {
    lines.push(
      `| ${book.title} | \`${book.editionId}\` | ${book.status} | ${book.stored.rows} | ${book.stored.verses} | ${book.expected.verses ?? 'unknown'} | ${book.missingVerses.length} | ${book.extraVerses.length} | ${book.corrupted.length} |`,
    );
  }
  lines.push('');
  for (const book of report.books) {
    lines.push(`## ${book.title} (\`${book.bookId}\`)`);
    lines.push('');
    lines.push(`- Edition: ${book.editionLabel}`);
    lines.push(`- Status: **${book.status}**`);
    lines.push(
      `- Stored: ${book.stored.rows} rows — ${book.stored.verses} verses, ${book.stored.groupedVerses} grouped, ${book.stored.speakers} speaker labels, ${book.stored.invocations} invocation/paratext, ${book.stored.unclassified} unclassified`,
    );
    if (book.provenance) {
      lines.push(`- Provenance kind: ${book.provenance.kind}`);
      lines.push(`- Independent collation: ${book.provenance.independentCollation ? 'yes' : 'NO'}`);
      lines.push(`- Rights status: ${book.provenance.rightsStatus}`);
      for (const file of book.provenance.sourceFiles) {
        lines.push(`  - \`${file.path}\` — ${file.bytes} bytes, sha256 \`${file.sha256.slice(0, 16)}…\``);
      }
    }
    if (book.chapters.length) {
      lines.push('');
      lines.push('| Ch | Expected verses | Stored verses | Stored rows | Missing | Complete |');
      lines.push('| --- | --- | --- | --- | --- | --- |');
      for (const chapter of book.chapters) {
        lines.push(
          `| ${chapter.chapter} | ${chapter.expectedVerses ?? '—'} | ${chapter.storedVerses} | ${chapter.storedRows} | ${chapter.missingVerseNumbers.length ? chapter.missingVerseNumbers.join(',') : '—'} | ${chapter.complete ? 'yes' : 'NO'} |`,
        );
      }
    }
    if (book.missingRanges.length) {
      lines.push('');
      lines.push(`Missing ranges: ${book.missingRanges.join(', ')}`);
    }
    lines.push('');
    for (const note of book.verificationNotes) lines.push(`> ${note}`);
    lines.push('');
  }
  lines.push('## Totals');
  lines.push('');
  lines.push(`- Books: ${report.totals.books} (with edition manifest: ${report.totals.booksWithEditionManifest})`);
  lines.push(`- Stored rows: ${report.totals.storedRows}`);
  lines.push(`- Missing verses vs manifest: ${report.totals.missingVerses}`);
  lines.push(`- Rows flagged corrupt: ${report.totals.corruptedRows}`);
  lines.push('');
  return lines.join('\n');
}

test('coverage report is generated and gated', async () => {
  __clearBookCache();
  const report = await buildCoverageReport({ fresh: true });
  report.generatedAt = new Date().toISOString();

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(JSON_PATH, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  fs.writeFileSync(MD_PATH, toMarkdown(report), 'utf8');

  const gita = report.books.find((b) => b.bookId === 'bhagavad-gita');
  expect(gita).toBeTruthy();
  expect(gita!.hasEditionManifest).toBe(true);
  expect(gita!.status).toBe('COMPLETE_FOR_EDITION');
  expect(gita!.missingVerses).toEqual([]);
  expect(gita!.extraVerses).toEqual([]);
  expect(gita!.duplicatePassageIds).toEqual([]);
  expect(gita!.corrupted).toEqual([]);
  expect(gita!.expected.verses).toBe(701);
  expect(gita!.stored.rows).toBe(770);
  expect(gita!.chapters).toHaveLength(18);
  for (const chapter of gita!.chapters) expect(chapter.complete).toBe(true);

  // The three fragmentary Granths must never be reported as complete.
  for (const bookId of ['ramcharitmanas', 'shiva-mahapuran', 'devi-bhagavata']) {
    const book = report.books.find((b) => b.bookId === bookId);
    expect(book).toBeTruthy();
    expect(book!.hasEditionManifest).toBe(false);
    expect(book!.status).toBe('NO_EDITION_MANIFEST');
    expect(book!.stored.rows).toBeGreaterThan(0);
    expect(book!.verificationNotes.join(' ')).toContain('No edition manifest');
  }

  expect(report.totals.missingVerses).toBe(0);
  expect(report.totals.corruptedRows).toBe(0);

  // Frozen summary: any drift in stored rows or manifest expectations shows up
  // here rather than silently changing the artefacts.
  expect(stableCoverageSummary(report)).toEqual([
    {
      bookId: 'bhagavad-gita',
      status: 'COMPLETE_FOR_EDITION',
      stored: { rows: 770, verses: 701, groupedVerses: 0, speakers: 60, invocations: 9, unclassified: 0, sections: 19 },
      expected: { verses: 701, rows: 770 },
      missingRanges: [],
      extraVerses: 0,
      duplicates: 0,
      repeatedParatext: 3,
      corrupted: 0,
    },
    {
      bookId: 'ramcharitmanas',
      status: 'NO_EDITION_MANIFEST',
      stored: { rows: 14, verses: 0, groupedVerses: 0, speakers: 0, invocations: 9, unclassified: 5, sections: 3 },
      expected: { verses: null, rows: null },
      missingRanges: [],
      extraVerses: 0,
      duplicates: 0,
      repeatedParatext: 0,
      corrupted: 0,
    },
    {
      bookId: 'shiva-mahapuran',
      status: 'NO_EDITION_MANIFEST',
      stored: { rows: 11, verses: 1, groupedVerses: 0, speakers: 0, invocations: 1, unclassified: 9, sections: 4 },
      expected: { verses: null, rows: null },
      missingRanges: [],
      extraVerses: 0,
      duplicates: 0,
      repeatedParatext: 0,
      corrupted: 0,
    },
    {
      bookId: 'devi-bhagavata',
      status: 'NO_EDITION_MANIFEST',
      stored: { rows: 6, verses: 0, groupedVerses: 0, speakers: 0, invocations: 5, unclassified: 1, sections: 3 },
      expected: { verses: null, rows: null },
      missingRanges: [],
      extraVerses: 0,
      duplicates: 0,
      repeatedParatext: 0,
      corrupted: 0,
    },
  ]);
});

test('every stored passage carries edition + checksum identity', async () => {
  const book = await loadBook('bhagavad-gita');
  expect(book.passages).toHaveLength(770);
  const ids = new Set<string>();
  const checksums = new Set<string>();
  for (const passage of book.passages) {
    expect(passage.checksum).toMatch(/^[0-9a-f]{64}$/);
    expect(passage.editionId).toBeTruthy();
    expect(passage.source.dataFile).toContain('bhagavad-gita');
    expect(passage.original.length).toBeGreaterThan(0);
    expect(ids.has(passage.passageId)).toBe(false);
    ids.add(passage.passageId);
    checksums.add(passage.checksum);
  }
  // Speaker rows repeat the same short label, so checksums must not be used as
  // the identity key; passage ids are.
  expect(ids.size).toBe(770);
});
