import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  metadataBase: new URL('https://cosmictantra.chiti.tech'),
  title: {
    default: 'CosmicTantra — Technology-Assisted Jyotish Operations',
    template: '%s | CosmicTantra',
  },
  description: 'Vedic Panchang ephemeris engine, 2026 Muhurat discovery, Janma Kundali generation, Vimshottari Dasha calculations, and verified traditional scholar consultations.',
  keywords: [
    'Vedic Astrology',
    'Jyotish',
    'Panchang',
    'Tithi Today',
    'Nakshatra Today',
    'Rahu Kaal',
    'Muhurat 2026',
    'Janma Kundali',
    'Vimshottari Dasha',
    'Varanasi Jyotishi',
    'Lahiri Ayanamsha',
    'Chiti Technologies',
  ],
  authors: [{ name: 'CosmicTantra Team', url: 'https://cosmictantra.chiti.tech' }],
  creator: 'Chiti Technologies',
  publisher: 'CosmicTantra',
  alternates: {
    canonical: 'https://cosmictantra.chiti.tech',
  },
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://cosmictantra.chiti.tech',
    siteName: 'CosmicTantra',
    title: 'CosmicTantra — Technology-Assisted Jyotish Operations',
    description: 'Vedic Panchang ephemeris engine, 2026 Muhurat discovery, Janma Kundali generation, Vimshottari Dasha calculations, and verified traditional scholar consultations.',
    images: [
      {
        url: 'https://cosmictantra.chiti.tech/varanasi-ghats-hero.jpg',
        width: 1200,
        height: 630,
        alt: 'CosmicTantra Vedic Astronomical Intelligence Interface',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CosmicTantra — Technology-Assisted Jyotish Operations',
    description: 'Vedic Panchang ephemeris engine, 2026 Muhurat discovery, Janma Kundali generation, and verified traditional scholar consultations.',
    images: ['https://cosmictantra.chiti.tech/varanasi-ghats-hero.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': 'https://cosmictantra.chiti.tech/#organization',
        'name': 'CosmicTantra',
        'url': 'https://cosmictantra.chiti.tech',
        'logo': 'https://cosmictantra.chiti.tech/varanasi-ghats-hero.jpg',
        'description': 'Technology-assisted Vedic Jyotish platform and sidereal ephemeris engine.',
        'sameAs': [
          'https://chiti.tech',
        ],
      },
      {
        '@type': 'WebSite',
        '@id': 'https://cosmictantra.chiti.tech/#website',
        'url': 'https://cosmictantra.chiti.tech',
        'name': 'CosmicTantra',
        'description': 'Vedic Astronomical Intelligence & Consultation Operations',
        'publisher': {
          '@id': 'https://cosmictantra.chiti.tech/#organization',
        },
      },
      {
        '@type': 'SoftwareApplication',
        'name': 'CosmicTantra Ephemeris Engine',
        'operatingSystem': 'Web',
        'applicationCategory': 'EducationalApplication',
        'offers': {
          '@type': 'Offer',
          'price': '0',
          'priceCurrency': 'INR',
        },
      },
      {
        '@type': 'FAQPage',
        'mainEntity': [
          {
            '@type': 'Question',
            'name': 'What ayanamsha does CosmicTantra use?',
            'acceptedAnswer': {
              '@type': 'Answer',
              'text': 'CosmicTantra calculates sidereal planetary positions using Chitra Paksha (Lahiri Standard) Ayanamsha with ±0.01° precision.',
            },
          },
          {
            '@type': 'Question',
            'name': 'How are consultation questions answered?',
            'acceptedAnswer': {
              '@type': 'Answer',
              'text': 'Consultation requests undergo a 5-stage verified practitioner pipeline where computational data is generated by our ephemeris engine and interpreted by traditional Jyotish scholars.',
            },
          },
        ],
      },
    ],
  };

  return (
    <html lang="en" className="dark">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="bg-[#FAF7F2] dark:bg-[#07080C] text-[#1C1917] dark:text-[#EFECE6] antialiased transition-colors duration-300">
        {children}
      </body>
    </html>
  );
}
