/**
 * CosmicTantra calendar festival artwork resolver.
 *
 * Resolves a day's panchang data to an artwork WebP under
 * `/assets/calendar/events/` following the manifest conventions in
 * `docs/EVENT_IMAGE_MANIFEST.json`.
 *
 * Resolution priority per day (first hit wins):
 *   1. a dedicated festival artwork for the first festival on the day;
 *   2. the festival's category fallback artwork (never an empty cell);
 *   3. the day's symbolic tithi artwork (30 tithi×paksha combos → 16 files).
 *
 * Every engine-emitted festival name (English) must be present in
 * `FESTIVAL_TOKENS`. `scripts/verify-artwork-coverage.ts` asserts 100% of the
 * days, festivals and tithi combos emitted by the real engine resolve to a
 * file that exists on disk — a missing token or asset fails the check.
 */

export interface DayArtwork {
  /** Absolute asset path beginning with `/assets/...` (served from /public). */
  src: string;
  /** Lightweight thumb for grid cells (384×216, generated by the build). */
  srcThumb: string;
  /** Human kind of artwork: festival | category | tithi. */
  kind: 'festival' | 'category' | 'tithi';
  /** Machine key (file name without extension) for tests/debug. */
  key: string;
  /** Short label, bilingual where the engine provides it. */
  label: string;
  labelHi: string;
  /** True when a festival-specific artwork was matched (sticker treatment). */
  isFestivalDay: boolean;
}

export interface ArtworkResolvable {
  tithi: { index?: number; name?: string; paksha?: string; [k: string]: unknown };
  festivals?: Array<{ name?: string; nameHi?: string; [k: string]: unknown }>;
  dateString?: string;
}

const BASE = '/assets/calendar/events';

/** Category fallbacks declared by EVENT_IMAGE_MANIFEST.json (8 files). */
export const CATEGORY_FALLBACKS: Record<string, string> = {
  SHIVA: 'shiva_generic_dhyana',
  VISHNU_KRISHNA: 'vishnu_krishna_generic',
  DEVI: 'devi_shakti_generic',
  GANESHA: 'ganesha_generic',
  SURYA: 'surya_sun_generic',
  RAM_HANUMAN: 'ram_hanuman_generic',
  MOON_PURNIMA: 'sharad_purnima_moon',
  FESTIVAL_LIGHTS: 'diwali_diyas',
};

/**
 * Token table: engine-emitted festival/vrat names (English `name` field from
 * `resolveFestivals` in `src/engines/monthlyPanchangEngine.ts`) → dedicated
 * artwork + category. Every distinct emitted name MUST appear here.
 */
interface TokenEntry {
  /** File name without extension under /assets/calendar/events. */
  art: string;
  category: keyof typeof CATEGORY_FALLBACKS;
  /**
   * Recurring universal vrats (Ekadashi/Purnima/Amavasya/…). When a day
   * carries both a generic vrat and a specific festival (e.g. Diwali on
   * Amavasya, Sharad Purnima on Purnima Vrat, Ganesh Chaturthi on Vinayaka
   * Chaturthi), the SPECIFIC festival's artwork must win — the generic token
   * only stands in when the day has no specific festival.
   */
  generic?: boolean;
}

export const FESTIVAL_TOKENS: Record<string, TokenEntry> = {
  // — Core manifest festivals (15 files) —
  'Krishna Janmashtami': { art: 'janmashtami', category: 'VISHNU_KRISHNA' },
  'Krishna Janmashtami (Smarta)': { art: 'janmashtami', category: 'VISHNU_KRISHNA' },
  'Ganesh Chaturthi (Ganeshotsav)': { art: 'ganesh_chaturthi', category: 'GANESHA' },
  'Sharad Navaratri Ghatasthapana': { art: 'navratri', category: 'DEVI' },
  'Chaitra Navaratri / Hindu New Year': { art: 'navavarsh', category: 'DEVI' },
  'Maha Ashtami / Durga Ashtami': { art: 'durga_ashtami', category: 'DEVI' },
  'Maha Navami / Ayudha Puja': { art: 'durga_ashtami', category: 'DEVI' },
  'Vijayadashami / Dussehra': { art: 'vijayadashami', category: 'RAM_HANUMAN' },
  'Diwali / Lakshmi Puja': { art: 'diwali', category: 'FESTIVAL_LIGHTS' },
  'Maha Shivaratri': { art: 'mahashivaratri', category: 'SHIVA' },
  'Chhath Puja (Sandhya Arghya)': { art: 'chhath_puja', category: 'SURYA' },
  'Sharad Purnima / Kojagari': { art: 'sharad_purnima', category: 'MOON_PURNIMA' },
  'Karwa Chauth Vrat': { art: 'karwa_chauth', category: 'DEVI' },
  'Raksha Bandhan / Shravani Upakarma': { art: 'raksha_bandhan', category: 'FESTIVAL_LIGHTS' },
  'Guru Purnima': { art: 'guru_purnima', category: 'MOON_PURNIMA' },
  'Makar Sankranti': { art: 'makar_sankranti', category: 'SURYA' },
  'Pradosha Vrat': { art: 'pradosh', category: 'SHIVA' },

  // — Expanded festival artworks (10 more files, this program) —
  'Holika Dahan / Holi': { art: 'holi', category: 'FESTIVAL_LIGHTS' },
  'Shri Ram Navami': { art: 'ram_navami', category: 'RAM_HANUMAN' },
  'Hanuman Jayanti': { art: 'hanuman_jayanti', category: 'RAM_HANUMAN' },
  'Dhanteras / Dhanvantari Jayanti': { art: 'dhanteras', category: 'FESTIVAL_LIGHTS' },
  'Govardhan Puja / Annakoot': { art: 'annakut', category: 'VISHNU_KRISHNA' },
  'Bhai Dooj / Yama Dwitiya': { art: 'bhai_dooj', category: 'FESTIVAL_LIGHTS' },
  'Kartika Purnima / Dev Deepawali': { art: 'dev_deepawali', category: 'FESTIVAL_LIGHTS' },
  'Vasant Panchami / Saraswati Puja': { art: 'vasant_panchami', category: 'DEVI' },
  'Nag Panchami': { art: 'nag_panchami', category: 'SHIVA' },

  // — Recurring vrats → reuse the closest dedicated artwork (never blank).
  // Marked `generic` so a same-day SPECIFIC festival wins the artwork.
  'Shukla Ekadashi Vrat': { art: 'ekadashi', category: 'VISHNU_KRISHNA', generic: true },
  'Krishna Ekadashi Vrat': { art: 'ekadashi', category: 'VISHNU_KRISHNA', generic: true },
  'Purnima Vrat / Satyanarayan Puja': { art: 'tithi_purnima', category: 'VISHNU_KRISHNA', generic: true },
  'Amavasya / Pitru Tarpana': { art: 'tithi_amavasya', category: 'MOON_PURNIMA', generic: true },
  'Vinayaka Chaturthi': { art: 'ganesh_chaturthi', category: 'GANESHA', generic: true },
  'Sankashti Chaturthi': { art: 'ganesh_chaturthi', category: 'GANESHA', generic: true },
  'Anant Chaturdashi': { art: 'vishnu_krishna_generic', category: 'VISHNU_KRISHNA' },
  'Narak Chaturdashi / Chhoti Diwali': { art: 'diwali', category: 'FESTIVAL_LIGHTS' },
};

/**
 * Tithi series (16 files) — the symbolic art that gives every ordinary day an
 * illustration. Tithi numbers 1..14 share an artwork across Shukla/Krishna
 * paksha; Purnima (Shukla 15) and Amavasya (Krishna 15) have their own files.
 */
export const TITHI_ART: Record<string, string> = {
  pratipada: 'tithi_pratipada',
  dwitiya: 'tithi_dwitiya',
  tritiya: 'tithi_tritiya',
  chaturthi: 'tithi_chaturthi',
  panchami: 'tithi_panchami',
  shashthi: 'tithi_shashthi',
  saptami: 'tithi_saptami',
  ashtami: 'tithi_ashtami',
  navami: 'tithi_navami',
  dashami: 'tithi_dashami',
  ekadashi: 'tithi_ekadashi',
  dwadashi: 'tithi_dwadashi',
  trayodashi: 'tithi_trayodashi',
  chaturdashi: 'tithi_chaturdashi',
  purnima: 'tithi_purnima',
  amavasya: 'tithi_amavasya',
};

const TITHI_NAME_TO_KEY: Record<string, string> = {
  Pratipada: 'pratipada',
  Dwitiya: 'dwitiya',
  Tritiya: 'tritiya',
  Chaturthi: 'chaturthi',
  Panchami: 'panchami',
  Shashthi: 'shashthi',
  Saptami: 'saptami',
  Ashtami: 'ashtami',
  Navami: 'navami',
  Dashami: 'dashami',
  Ekadashi: 'ekadashi',
  Dwadashi: 'dwadashi',
  Trayodashi: 'trayodashi',
  Chaturdashi: 'chaturdashi',
};

const TITHI_LABEL_HI: Record<string, string> = {
  pratipada: 'प्रतिपदा',
  dwitiya: 'द्वितीया',
  tritiya: 'तृतीया',
  chaturthi: 'चतुर्थी',
  panchami: 'पञ्चमी',
  shashthi: 'षष्ठी',
  saptami: 'सप्तमी',
  ashtami: 'अष्टमी',
  navami: 'नवमी',
  dashami: 'दशमी',
  ekadashi: 'एकादशी',
  dwadashi: 'द्वादशी',
  trayodashi: 'त्रयोदशी',
  chaturdashi: 'चतुर्दशी',
  purnima: 'पूर्णिमा',
  amavasya: 'अमावस्या',
};

/** Normalise any engine tithi shape to an artwork file key. */
export function resolveTithiArtKey(tithi: ArtworkResolvable['tithi']): string | null {
  if (!tithi) return null;
  const name = typeof tithi.name === 'string' ? tithi.name.trim() : '';
  // The month engine stores index 1..30 (see PanchangDayData.tithi.index).
  const rawIndex = tithi.index;
  if (typeof rawIndex === 'number' && rawIndex >= 1 && rawIndex <= 30) {
    const idx = Math.round(rawIndex);
    if (idx === 15) return TITHI_ART.purnima;
    if (idx === 30) return TITHI_ART.amavasya;
    const key = TITHI_NAME_TO_KEY[TITHIS_BY_INDEX[(idx - 1) % 15]];
    if (key) return TITHI_ART[key];
  }
  // Fall back on the English bare name.
  const key = TITHI_NAME_TO_KEY[name];
  if (key) return TITHI_ART[key];
  if (/purnima|पूर्णिमा/i.test(name)) return TITHI_ART.purnima;
  if (/amavasya|अमावस्या/i.test(name)) return TITHI_ART.amavasya;
  return null;
}

const TITHIS_BY_INDEX = [
  'Pratipada', 'Dwitiya', 'Tritiya', 'Chaturthi', 'Panchami',
  'Shashthi', 'Saptami', 'Ashtami', 'Navami', 'Dashami',
  'Ekadashi', 'Dwadashi', 'Trayodashi', 'Chaturdashi', 'Purnima',
];

function asset(key: string): DayArtwork['src'] {
  return `${BASE}/${key}.webp`;
}

function thumb(key: string): DayArtwork['srcThumb'] {
  return `${BASE}/${key}-sm.webp`;
}

function toArtwork(key: string, kind: DayArtwork['kind'], label: string, labelHi: string, isFestivalDay: boolean): DayArtwork {
  return { src: asset(key), srcThumb: thumb(key), kind, key, label, labelHi, isFestivalDay };
}

/**
 * Resolve artwork for one calendar day.
 *
 * Festival days get their dedicated (or category) artwork and
 * `isFestivalDay: true` — the UI renders them with the richer "sticker" cell.
 * Ordinary days always resolve to the symbolic tithi artwork, so no cell is
 * ever blank. Returns null only for truly unrepresentable input (no tithi at
 * all), which callers should treat as "no art".
 */
export function resolveDayArtwork(day: ArtworkResolvable): DayArtwork | null {
  const festivals = Array.isArray(day.festivals) ? day.festivals : [];
  const fname = (f: { name?: unknown }) => (typeof f?.name === 'string' ? f.name : '');
  const fnameHi = (f: { nameHi?: unknown }) => (typeof f?.nameHi === 'string' ? f.nameHi : '');

  // Pass 1 — specific (non-generic) festival artwork. On days that carry both
  // a specific festival and a universal vrat (Diwali on Amavasya, Sharad
  // Purnima on Purnima Vrat, Ganesh Chaturthi on Vinayaka Chaturthi) the
  // SPECIFIC artwork must win regardless of emission order.
  for (const f of festivals) {
    const token = FESTIVAL_TOKENS[fname(f)];
    if (token && !token.generic) {
      return toArtwork(token.art, 'festival', fname(f), fnameHi(f), true);
    }
  }

  // Pass 2 — generic vrat token, else keyword category for unknown names.
  let categoryArt: DayArtwork | null = null;
  for (const f of festivals) {
    const token = FESTIVAL_TOKENS[fname(f)];
    if (token) {
      return toArtwork(token.art, 'festival', fname(f), fnameHi(f), true);
    }
    const cat = categoryByKeyword(fname(f));
    if (cat && !categoryArt) {
      const key = CATEGORY_FALLBACKS[cat];
      categoryArt = toArtwork(key, 'category', fname(f), fnameHi(f), true);
    }
  }
  if (categoryArt) return categoryArt;

  // Pass 3 — symbolic tithi artwork so ordinary days are never blank.
  const tithiKey = resolveTithiArtKey(day.tithi);
  if (tithiKey) {
    const tithiName = typeof day.tithi.name === 'string' ? day.tithi.name : '';
    return toArtwork(
      tithiKey,
      'tithi',
      `Tithi • ${tithiName || ''}`.trim(),
      `${TITHI_LABEL_HI[tithiKey] || ''} तिथि`,
      false
    );
  }
  return null;
}

function categoryByKeyword(name: string): keyof typeof CATEGORY_FALLBACKS | null {
  const n = name.toLowerCase();
  if (n.includes('shiva') || n.includes('शिव')) return 'SHIVA';
  if (n.includes('vishnu') || n.includes('krishna') || n.includes('जन्माष्टमी') || n.includes('विष्णु')) return 'VISHNU_KRISHNA';
  if (n.includes('durga') || n.includes('devi') || n.includes('lakshmi') || n.includes('saraswati') || n.includes('दुर्गा')) return 'DEVI';
  if (n.includes('ganesh') || n.includes('गणेश')) return 'GANESHA';
  if (n.includes('surya') || n.includes('sankranti') || n.includes('छठ') || n.includes('सूर्य')) return 'SURYA';
  if (n.includes('hanuman') || n.includes('ram') || n.includes('राम') || n.includes('हनुमान')) return 'RAM_HANUMAN';
  if (n.includes('purnima') || n.includes('moon') || n.includes('पूर्णिमा')) return 'MOON_PURNIMA';
  if (n.includes('diwali') || n.includes('deep') || n.includes('diyas') || n.includes('दीप')) return 'FESTIVAL_LIGHTS';
  return null;
}

/** All artwork keys referenced by the token/category/tithi tables (for tests). */
export const ALL_ARTWORK_KEYS: Set<string> = (() => {
  const s = new Set<string>(Object.values(CATEGORY_FALLBACKS));
  for (const e of Object.values(FESTIVAL_TOKENS)) s.add(e.art);
  for (const v of Object.values(TITHI_ART)) s.add(v);
  return s;
})();
